#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimNotify_BPShoot

#include "Basic.hpp"

#include "Runtime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AnimNotify_BPShoot.AnimNotify_BPShoot_C
// 0x0000 (0x0088 - 0x0088)
class UAnimNotify_BPShoot_C final : public UAnimNotify_Shoot
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("AnimNotify_BPShoot_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AnimNotify_BPShoot_C")
	}
	static class UAnimNotify_BPShoot_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAnimNotify_BPShoot_C>();
	}
};
DUMPER7_ASSERTS_UAnimNotify_BPShoot_C;

}

