#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_2RailLDCameraActor

#include "Basic.hpp"

#include "BP_2RailLDCameraActor_classes.hpp"
#include "BP_2RailLDCameraActor_parameters.hpp"


namespace SDK
{

// Function BP_2RailLDCameraActor.BP_2RailLDCameraActor_C.UpdateTimeAndSplineFollowActor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_2RailLDCameraActor_C::UpdateTimeAndSplineFollowActor(double DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_2RailLDCameraActor_C", "UpdateTimeAndSplineFollowActor");

	Params::BP_2RailLDCameraActor_C_UpdateTimeAndSplineFollowActor Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_2RailLDCameraActor.BP_2RailLDCameraActor_C.UpdateTimeAndSplineLookAtActor
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_2RailLDCameraActor_C::UpdateTimeAndSplineLookAtActor(double DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_2RailLDCameraActor_C", "UpdateTimeAndSplineLookAtActor");

	Params::BP_2RailLDCameraActor_C_UpdateTimeAndSplineLookAtActor Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_2RailLDCameraActor.BP_2RailLDCameraActor_C.UpdateCameraPositionAndLookAt
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_2RailLDCameraActor_C::UpdateCameraPositionAndLookAt(double DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_2RailLDCameraActor_C", "UpdateCameraPositionAndLookAt");

	Params::BP_2RailLDCameraActor_C_UpdateCameraPositionAndLookAt Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_2RailLDCameraActor.BP_2RailLDCameraActor_C.ScrubDebugTime
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_2RailLDCameraActor_C::ScrubDebugTime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_2RailLDCameraActor_C", "ScrubDebugTime");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_2RailLDCameraActor.BP_2RailLDCameraActor_C.GlobalDebug
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_2RailLDCameraActor_C::GlobalDebug()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_2RailLDCameraActor_C", "GlobalDebug");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_2RailLDCameraActor.BP_2RailLDCameraActor_C.GetDebugTime2
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double*                                 DebugTime2_0                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_2RailLDCameraActor_C::GetDebugTime2(double* DebugTime2_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_2RailLDCameraActor_C", "GetDebugTime2");

	Params::BP_2RailLDCameraActor_C_GetDebugTime2 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (DebugTime2_0 != nullptr)
		*DebugTime2_0 = Parms.DebugTime2_0;
}


// Function BP_2RailLDCameraActor.BP_2RailLDCameraActor_C.DrawDebug2
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Time1                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Time2                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector*                         TargetPos                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_2RailLDCameraActor_C::DrawDebug2(double Time1, double Time2, struct FVector* TargetPos)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_2RailLDCameraActor_C", "DrawDebug2");

	Params::BP_2RailLDCameraActor_C_DrawDebug2 Parms{};

	Parms.Time1 = Time1;
	Parms.Time2 = Time2;

	UObject::ProcessEvent(Func, &Parms);

	if (TargetPos != nullptr)
		*TargetPos = std::move(Parms.TargetPos);
}


// Function BP_2RailLDCameraActor.BP_2RailLDCameraActor_C.GetCurrentTime2
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float ABP_2RailLDCameraActor_C::GetCurrentTime2() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_2RailLDCameraActor_C", "GetCurrentTime2");

	Params::BP_2RailLDCameraActor_C_GetCurrentTime2 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_2RailLDCameraActor.BP_2RailLDCameraActor_C.GetCurrentFramingSystemTime2
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// double*                                 Current_Framing_System_Time_2_0                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_2RailLDCameraActor_C::GetCurrentFramingSystemTime2(double* Current_Framing_System_Time_2_0) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_2RailLDCameraActor_C", "GetCurrentFramingSystemTime2");

	Params::BP_2RailLDCameraActor_C_GetCurrentFramingSystemTime2 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Current_Framing_System_Time_2_0 != nullptr)
		*Current_Framing_System_Time_2_0 = Parms.Current_Framing_System_Time_2_0;
}

}

