#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AimCameraSpeedOption

#include "Basic.hpp"

#include "SCCore_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AimCameraSpeedOption.BP_AimCameraSpeedOption_C
// 0x0000 (0x0030 - 0x0030)
class UBP_AimCameraSpeedOption_C final : public UGameOption
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AimCameraSpeedOption_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AimCameraSpeedOption_C")
	}
	static class UBP_AimCameraSpeedOption_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AimCameraSpeedOption_C>();
	}
};
DUMPER7_ASSERTS_UBP_AimCameraSpeedOption_C;

}

