#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BinderRecorder

#include "Basic.hpp"

#include "Runtime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BinderRecorder.BP_BinderRecorder_C
// 0x0000 (0x00F8 - 0x00F8)
class UBP_BinderRecorder_C final : public URTBinderRecorder
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BinderRecorder_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BinderRecorder_C")
	}
	static class UBP_BinderRecorder_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BinderRecorder_C>();
	}
};
DUMPER7_ASSERTS_UBP_BinderRecorder_C;

}

