#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BallControlV0AnimMetadata

#include "Basic.hpp"

#include "BP_BallControlAnimMetadata_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BallControlV0AnimMetadata.BP_BallControlV0AnimMetadata_C
// 0x0000 (0x03E0 - 0x03E0)
class UBP_BallControlV0AnimMetadata_C final : public UBP_BallControlAnimMetadata_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BallControlV0AnimMetadata_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BallControlV0AnimMetadata_C")
	}
	static class UBP_BallControlV0AnimMetadata_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BallControlV0AnimMetadata_C>();
	}
};
DUMPER7_ASSERTS_UBP_BallControlV0AnimMetadata_C;

}

