#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Binder_BallInfluence

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Runtime_structs.hpp"
#include "BP_Binder_BallAnyOwnerChanged_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Binder_BallInfluence.BP_Binder_BallInfluence_C
// 0x0008 (0x03B0 - 0x03A8)
class UBP_Binder_BallInfluence_C final : public UBP_Binder_BallAnyOwnerChanged_C
{
public:
	uint8                                         Pad_3A2[0x6];                                      // 0x03A2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Binder_BallInfluence_C;          // 0x03A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void BPE_OnBallReset(class UBallPlayersInteractionComponent* _ballPlayersInteraction);
	bool Can_Trigger(class UBallPlayersInteractionComponent* BallPlayersInteraction, const struct FShootParams& ShootParams, EBallInteractionType _eBallInteractionType);
	void ExecuteUbergraph_BP_Binder_BallInfluence(int32 EntryPoint);
	void PrepareData(class UBallPlayersInteractionComponent* _ballPlayersInteraction, EBallInteractionType _eBallInteractionType);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Binder_BallInfluence_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Binder_BallInfluence_C")
	}
	static class UBP_Binder_BallInfluence_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Binder_BallInfluence_C>();
	}
};
DUMPER7_ASSERTS_UBP_Binder_BallInfluence_C;

}

