#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Binder_BallChangeOwnership

#include "Basic.hpp"

#include "BP_Binder_BallChangeOwnership_classes.hpp"
#include "BP_Binder_BallChangeOwnership_parameters.hpp"


namespace SDK
{

// Function BP_Binder_BallChangeOwnership.BP_Binder_BallChangeOwnership_C.PrepareData
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBallPlayersInteractionComponent* _ballPlayersInteraction                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// EBallInteractionType                    _eBallInteractionType                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_Binder_BallChangeOwnership_C::PrepareData(class UBallPlayersInteractionComponent* _ballPlayersInteraction, EBallInteractionType _eBallInteractionType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Binder_BallChangeOwnership_C", "PrepareData");

	Params::BP_Binder_BallChangeOwnership_C_PrepareData Parms{};

	Parms._ballPlayersInteraction = _ballPlayersInteraction;
	Parms._eBallInteractionType = _eBallInteractionType;

	UObject::ProcessEvent(Func, &Parms);
}

}

