#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CelebrationFreeRunHandler

#include "Basic.hpp"

#include "Runtime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CelebrationFreeRunHandler.BP_CelebrationFreeRunHandler_C
// 0x0000 (0x0610 - 0x0610)
class UBP_CelebrationFreeRunHandler_C final : public UCelebrationHandlerFlowState
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CelebrationFreeRunHandler_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CelebrationFreeRunHandler_C")
	}
	static class UBP_CelebrationFreeRunHandler_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CelebrationFreeRunHandler_C>();
	}
};
DUMPER7_ASSERTS_UBP_CelebrationFreeRunHandler_C;

}

