#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CustomizationPresetListViewModel

#include "Basic.hpp"

#include "BP_CustomizationPresetListViewModel_classes.hpp"
#include "BP_CustomizationPresetListViewModel_parameters.hpp"


namespace SDK
{

// Function BP_CustomizationPresetListViewModel.BP_CustomizationPresetListViewModel_C.CanCreatePreset
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool*                                   CanCreatePreset_0                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_CustomizationPresetListViewModel_C::CanCreatePreset(bool* CanCreatePreset_0) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomizationPresetListViewModel_C", "CanCreatePreset");

	Params::BP_CustomizationPresetListViewModel_C_CanCreatePreset Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (CanCreatePreset_0 != nullptr)
		*CanCreatePreset_0 = Parms.CanCreatePreset_0;
}


// Function BP_CustomizationPresetListViewModel.BP_CustomizationPresetListViewModel_C.GetEquippedPresetViewModel
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class UCustomizationPresetViewModel**   Output                                                 (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_CustomizationPresetListViewModel_C::GetEquippedPresetViewModel(class UCustomizationPresetViewModel** Output) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CustomizationPresetListViewModel_C", "GetEquippedPresetViewModel");

	Params::BP_CustomizationPresetListViewModel_C_GetEquippedPresetViewModel Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = Parms.Output;
}

}

