#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CountdowGameFlowState

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Runtime_classes.hpp"
#include "SCCore_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CountdowGameFlowState.BP_CountdowGameFlowState_C
// 0x0008 (0x0598 - 0x0590)
class UBP_CountdowGameFlowState_C final : public URuntimeGameFlowState
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0590(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void BPE_EnteringFlowState(class USCGameFlowSubsystem* _gameFlowSubsystem, const class USCGameFlowState* PreviousState);
	void BPE_ExitingFlowState(class USCGameFlowSubsystem* _gameFlowSubsystem, const class USCGameFlowState* _nextState, bool _bIsBackTracking);
	void ExecuteUbergraph_BP_CountdowGameFlowState(int32 EntryPoint);
	void OnCountdownOver(class ARuntimeMatchGameState* _gameState);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CountdowGameFlowState_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CountdowGameFlowState_C")
	}
	static class UBP_CountdowGameFlowState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_CountdowGameFlowState_C>();
	}
};
DUMPER7_ASSERTS_UBP_CountdowGameFlowState_C;

}

