#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ExtraEffortAutoTapAbilityData

#include "Basic.hpp"

#include "Runtime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ExtraEffortAutoTapAbilityData.BP_ExtraEffortAutoTapAbilityData_C
// 0x0000 (0x0110 - 0x0110)
class UBP_ExtraEffortAutoTapAbilityData_C final : public UShootAbilityData
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ExtraEffortAutoTapAbilityData_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ExtraEffortAutoTapAbilityData_C")
	}
	static class UBP_ExtraEffortAutoTapAbilityData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ExtraEffortAutoTapAbilityData_C>();
	}
};
DUMPER7_ASSERTS_UBP_ExtraEffortAutoTapAbilityData_C;

}

