#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_GameplayPhaseSubsystem

#include "Basic.hpp"

#include "Runtime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_GameplayPhaseSubsystem.BP_GameplayPhaseSubsystem_C
// 0x0000 (0x0290 - 0x0290)
class UBP_GameplayPhaseSubsystem_C final : public URTGameplayPhaseSubsystem
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_GameplayPhaseSubsystem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_GameplayPhaseSubsystem_C")
	}
	static class UBP_GameplayPhaseSubsystem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_GameplayPhaseSubsystem_C>();
	}
};
DUMPER7_ASSERTS_UBP_GameplayPhaseSubsystem_C;

}

