#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_LockMoveGoalKeeperAnimDatasource

#include "Basic.hpp"

#include "SCCore_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_LockMoveGoalKeeperAnimDatasource.BP_LockMoveGoalKeeperAnimDatasource_C
// 0x0000 (0x01E8 - 0x01E8)
class UBP_LockMoveGoalKeeperAnimDatasource_C final : public USpeedStateTargetDatasource
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_LockMoveGoalKeeperAnimDatasource_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_LockMoveGoalKeeperAnimDatasource_C")
	}
	static class UBP_LockMoveGoalKeeperAnimDatasource_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_LockMoveGoalKeeperAnimDatasource_C>();
	}
};
DUMPER7_ASSERTS_UBP_LockMoveGoalKeeperAnimDatasource_C;

}

