#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ProtectAnimSequencePicker

#include "Basic.hpp"

#include "SCCore_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ProtectAnimSequencePicker.BP_ProtectAnimSequencePicker_C
// 0x0000 (0x0200 - 0x0200)
class UBP_ProtectAnimSequencePicker_C final : public UAnimSequencePickerContainer
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ProtectAnimSequencePicker_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ProtectAnimSequencePicker_C")
	}
	static class UBP_ProtectAnimSequencePicker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ProtectAnimSequencePicker_C>();
	}
};
DUMPER7_ASSERTS_UBP_ProtectAnimSequencePicker_C;

}

