#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerScoreGlobalContainerVM

#include "Basic.hpp"

#include "Runtime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PlayerScoreGlobalContainerVM.BP_PlayerScoreGlobalContainerVM_C
// 0x0000 (0x01B0 - 0x01B0)
class UBP_PlayerScoreGlobalContainerVM_C final : public URuntimePlayerScoreGlobalContainerViewModel
{
public:
	int32 GetAwayTeamTotalScore() const;
	void GetFirstPlayerScoreVM(class UPlayerScoreViewModel** OutPlayerScoreVM) const;
	void GetFirstPlayerScoreVMAsArray(TArray<class UPlayerScoreViewModel*>* OutPlayerScoreVM) const;
	void GetFirstTeamList(TArray<class UPlayerScoreViewModel*>* Output_Get) const;
	int32 GetHomeTeamTotalScore() const;
	void GetLocalPlayerScoreVM(class UPlayerScoreViewModel** OutPlayerScoreVM) const;
	void GetLocalPlayerScoreVMAsArray(TArray<class UPlayerScoreViewModel*>* ScoreCounters) const;
	void GetSecondTeamList(TArray<class UPlayerScoreViewModel*>* Output_Get) const;
	void GetTeamListFromTeamIndex(uint8 TeamIndex, TArray<class UPlayerScoreViewModel*>* Output_Get) const;
	void GetTeamScoreTotal(uint8 _uiTeam, int32* TeamScoreTotal) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PlayerScoreGlobalContainerVM_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PlayerScoreGlobalContainerVM_C")
	}
	static class UBP_PlayerScoreGlobalContainerVM_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_PlayerScoreGlobalContainerVM_C>();
	}
};
DUMPER7_ASSERTS_UBP_PlayerScoreGlobalContainerVM_C;

}

