#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_RuntimeCheatManager

#include "Basic.hpp"

#include "Runtime_structs.hpp"
#include "Runtime_classes.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_RuntimeCheatManager.BP_RuntimeCheatManager_C
// 0x0100 (0x0188 - 0x0088)
class UBP_RuntimeCheatManager_C final : public URuntimeCheatManager
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0088(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          bIsOverridingCameraPreset;                         // 0x0090(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_SCControllerDebug_C*               ControllerDebug;                                   // 0x0098(0x0008)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        DebugBallForwardTeleportDistance;                  // 0x00A0(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        TimeDilationMultiplier;                            // 0x00A8(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class FString>                         Forced_Render_Stats;                               // 0x00B0(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly)
	TMap<class FName, class FString>              CmdDisplayNameToCmd;                               // 0x00C0(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly)
	bool                                          IsDebugCommandsOn;                                 // 0x0110(0x0001)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_111[0x7];                                      // 0x0111(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                BallSavedPosition;                                 // 0x0118(0x0018)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                PlayerSavedPosition;                               // 0x0130(0x0018)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                PlayerSavedRota;                                   // 0x0148(0x0018)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                BallSavedVelocity;                                 // 0x0160(0x0018)(Edit, BlueprintVisible, ZeroConstructor, Transient, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          SimplifiedCustoEnabled;                            // 0x0178(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_179[0x7];                                      // 0x0179(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ASCGameState*                           RegisteredGameState;                               // 0x0180(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, Transient, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ActivateDiveAimAssist(bool bToggled);
	void CmdHideHUD(bool bToggled);
	void Debug_AI_Spawn(EAITeamOnSpawn _Spawn_Parameters_Team_On_Spawn, double B, const struct FVector& InputPin);
	void ExecuteDebugCmd(class FName CmdName);
	void ExecuteUbergraph_BP_RuntimeCheatManager(int32 EntryPoint);
	void InpActEvt_Add_K2Node_InputKeyEvent_4(const struct FKey& Key);
	void InpActEvt_Alt_A_AccentGrave_K2Node_InputKeyEvent_6(const struct FKey& Key);
	void InpActEvt_Alt_NumPadZero_K2Node_InputKeyEvent_7(const struct FKey& Key);
	void InpActEvt_Alt_Zero_K2Node_InputKeyEvent_5(const struct FKey& Key);
	void InpActEvt_Gamepad_DPad_Left_K2Node_InputKeyEvent_1(const struct FKey& Key);
	void InpActEvt_Gamepad_DPad_Up_K2Node_InputKeyEvent_2(const struct FKey& Key);
	void InpActEvt_NumPadEight_K2Node_InputKeyEvent_10(const struct FKey& Key);
	void InpActEvt_NumPadFive_K2Node_InputKeyEvent_12(const struct FKey& Key);
	void InpActEvt_NumPadNine_K2Node_InputKeyEvent_9(const struct FKey& Key);
	void InpActEvt_NumPadOne_K2Node_InputKeyEvent_8(const struct FKey& Key);
	void InpActEvt_NumPadTwo_K2Node_InputKeyEvent_11(const struct FKey& Key);
	void InpActEvt_R_K2Node_InputKeyEvent_0(const struct FKey& Key);
	void InpActEvt_Subtract_K2Node_InputKeyEvent_3(const struct FKey& Key);
	bool Is_Controller_Debug_Displayed(class FName ActionName);
	void On_Simplified_Custo_Changed(bool bToggled);
	void On_Toggle_Display_Controller_Debug_Changed(bool bToggled);
	void OnPawnChanged(class APlayerState* Player, class APawn* NewPawn, class APawn* OldPawn);
	void OnPawnSet(class APawn* InPawn);
	void OnPlayerStateAdded(class APlayerState* _PlayerStateAdded);
	void ReceiveEndPlay();
	void ReceiveInitCheatManager();
	void RefreshPawns();
	void RegisterDebugCmds();
	void ResetSteamAchievements(class FName ActionName);
	void ServerRefillFullStamina(class AActor* InTarget);
	void ServerResetBallAtLocation(const struct FVector& InLocation);
	void ServerResetBallVelocity(const struct FVector& Pos, const struct FVector& Velocity);
	void ServerResetCharacterAtLocationAndRotation(const struct FVector& Pos, const struct FRotator& Rot);
	void ServerSpawnBall(class ARuntimeCharacter* InActor, bool TakeBall);
	void SetControllerDebugInViewport();
	void Setup_Spawn_AI_Event();
	void SetupAchievementsDebug();
	void ShowForcedRenderStats();
	void SnapNearestBall(bool MenuEnumHandler, bool TakeBall);
	void Spawn_AI_As_Opponent(class FName ActionName);
	void Spawn_AI_As_Teammate(class FName ActionName);
	void Spawn_both_teams(class FName ActionName);
	void ToggleDebug(bool bToggled);
	void ToggleMarketCameraPreset(class FName ActionName);
	void Trigger_Save_Progression_Achievement(class FName ActionName);
	void TriggerPrologueAchievement(class FName ActionName);

	void Can_Execute_Debug_Commands(bool* Result) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_RuntimeCheatManager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_RuntimeCheatManager_C")
	}
	static class UBP_RuntimeCheatManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_RuntimeCheatManager_C>();
	}
};
DUMPER7_ASSERTS_UBP_RuntimeCheatManager_C;

}

