#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StartDashNotify

#include "Basic.hpp"

#include "SCCore_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_StartDashNotify.BP_StartDashNotify_C
// 0x0000 (0x0088 - 0x0088)
class UBP_StartDashNotify_C final : public UTimeStretchNotify
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_StartDashNotify_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_StartDashNotify_C")
	}
	static class UBP_StartDashNotify_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_StartDashNotify_C>();
	}
};
DUMPER7_ASSERTS_UBP_StartDashNotify_C;

}

