#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TackleForceDependingSpeed

#include "Basic.hpp"

#include "BP_TackleForceDependingSpeed_classes.hpp"
#include "BP_TackleForceDependingSpeed_parameters.hpp"


namespace SDK
{

// Function BP_TackleForceDependingSpeed.BP_TackleForceDependingSpeed_C.BPE_ApplyMultiplierForce
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// const class AActor*                     _actor                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FShootPrepTargetData&      _ShootData                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UBP_TackleForceDependingSpeed_C::BPE_ApplyMultiplierForce(const class AActor* _actor, const struct FShootPrepTargetData& _ShootData) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TackleForceDependingSpeed_C", "BPE_ApplyMultiplierForce");

	Params::BP_TackleForceDependingSpeed_C_BPE_ApplyMultiplierForce Parms{};

	Parms._actor = _actor;
	Parms._ShootData = std::move(_ShootData);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

