#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VolleyPushBall_FrictionTrajectoryModifier

#include "Basic.hpp"

#include "Runtime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_VolleyPushBall_FrictionTrajectoryModifier.BP_VolleyPushBall_FrictionTrajectoryModifier_C
// 0x0000 (0x0078 - 0x0078)
class UBP_VolleyPushBall_FrictionTrajectoryModifier_C final : public UFrictionTrajectoryModifier
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_VolleyPushBall_FrictionTrajectoryModifier_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_VolleyPushBall_FrictionTrajectoryModifier_C")
	}
	static class UBP_VolleyPushBall_FrictionTrajectoryModifier_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_VolleyPushBall_FrictionTrajectoryModifier_C>();
	}
};
DUMPER7_ASSERTS_UBP_VolleyPushBall_FrictionTrajectoryModifier_C;

}

