#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VolleyShootSnap

#include "Basic.hpp"

#include "SCCore_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_VolleyShootSnap.BP_VolleyShootSnap_C
// 0x0000 (0x0080 - 0x0080)
class UBP_VolleyShootSnap_C final : public USnapComputationContainer
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_VolleyShootSnap_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_VolleyShootSnap_C")
	}
	static class UBP_VolleyShootSnap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_VolleyShootSnap_C>();
	}
};
DUMPER7_ASSERTS_UBP_VolleyShootSnap_C;

}

