#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DefaultGamepadPreset_LevelSequence

#include "Basic.hpp"

#include "SCCore_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DefaultGamepadPreset_LevelSequence.DefaultGamepadPreset_LevelSequence_C
// 0x0000 (0x00C8 - 0x00C8)
class UDefaultGamepadPreset_LevelSequence_C final : public UInputMappingPresetDB
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DefaultGamepadPreset_LevelSequence_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DefaultGamepadPreset_LevelSequence_C")
	}
	static class UDefaultGamepadPreset_LevelSequence_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDefaultGamepadPreset_LevelSequence_C>();
	}
};
DUMPER7_ASSERTS_UDefaultGamepadPreset_LevelSequence_C;

}

