#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EGenders

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EGenders.EGenders
// NumValues: 0x0004
enum class EGenders : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	EGenders_MAX                             = 3,
};

}

