#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EPlayerProfileCategories

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EPlayerProfileCategories.EPlayerProfileCategories
// NumValues: 0x0006
enum class EPlayerProfileCategories : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator4                           = 4,
	EPlayerProfileCategories_MAX             = 5,
};

}

