#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EVFXFootSide

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EVFXFootSide.EVFXFootSide
// NumValues: 0x0003
enum class EVFXFootSide : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	EVFXFootSide_MAX                         = 2,
};

}

