#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Finisher_Gesture_Gratitude_Sequence

#include "Basic.hpp"

#include "MovieScene_structs.hpp"


namespace SDK::Params
{

// Function Finisher_Gesture_Gratitude_Sequence.Finisher_Gesture_Gratitude_Sequence_DirectorBP_C.Scorer_DynamicBinding
// 0x0020 (0x0020 - 0x0000)
struct Finisher_Gesture_Gratitude_Sequence_DirectorBP_C_Scorer_DynamicBinding final
{
public:
	struct FMovieSceneDynamicBindingResolveResult ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ReturnParm, NoDestructor)
	struct FMovieSceneDynamicBindingResolveResult CallFunc_GoalScorer_ReturnValue;                   // 0x0010(0x0010)(NoDestructor)
};
DUMPER7_ASSERTS_Finisher_Gesture_Gratitude_Sequence_DirectorBP_C_Scorer_DynamicBinding;

}

