#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_BallSteal_ExhaustedBlock_GoalKeeper

#include "Basic.hpp"


namespace SDK::Params
{

// Function GA_BallSteal_ExhaustedBlock_GoalKeeper.GA_BallSteal_ExhaustedBlock_GoalKeeper_C.HasBallControlNeededTag
// 0x0001 (0x0001 - 0x0000)
struct GA_BallSteal_ExhaustedBlock_GoalKeeper_C_HasBallControlNeededTag final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GA_BallSteal_ExhaustedBlock_GoalKeeper_C_HasBallControlNeededTag;

}

