#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_DiveHorizontal

#include "Basic.hpp"

#include "GA_DiveHorizontal_classes.hpp"
#include "GA_DiveHorizontal_parameters.hpp"


namespace SDK
{

// Function GA_DiveHorizontal.GA_DiveHorizontal_C.BPE_BuildPayload
// (Event, Public, BlueprintEvent)

void UGA_DiveHorizontal_C::BPE_BuildPayload()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "BPE_BuildPayload");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_DiveHorizontal_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_DiveHorizontal_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "K2_OnEndAbility");

	Params::GA_DiveHorizontal_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.ExecuteUbergraph_GA_DiveHorizontal
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_DiveHorizontal_C::ExecuteUbergraph_GA_DiveHorizontal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "ExecuteUbergraph_GA_DiveHorizontal");

	Params::GA_DiveHorizontal_C_ExecuteUbergraph_GA_DiveHorizontal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.ShouldReorientFallback
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FInputGameplayAbilityTargetData&InputTargetData                                        (BlueprintVisible, BlueprintReadOnly, Parm)
// const struct FBallInterceptionPointTargetData&BallInterceptionTargetData                             (BlueprintVisible, BlueprintReadOnly, Parm)
// bool*                                   Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_DiveHorizontal_C::ShouldReorientFallback(const struct FInputGameplayAbilityTargetData& InputTargetData, const struct FBallInterceptionPointTargetData& BallInterceptionTargetData, bool* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "ShouldReorientFallback");

	Params::GA_DiveHorizontal_C_ShouldReorientFallback Parms{};

	Parms.InputTargetData = std::move(InputTargetData);
	Parms.BallInterceptionTargetData = std::move(BallInterceptionTargetData);

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.Reset Buildup Vars
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::Reset_Buildup_Vars()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "Reset Buildup Vars");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.ReprojectFallbackHitOntoInputDir
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::ReprojectFallbackHitOntoInputDir()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "ReprojectFallbackHitOntoInputDir");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.IsNewBallInterceptionPreferred
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FBallInterceptionPointTargetData&BaseBallInterception                                   (BlueprintVisible, BlueprintReadOnly, Parm)
// const struct FBallInterceptionPointTargetData&NewBallInterception                                    (BlueprintVisible, BlueprintReadOnly, Parm)
// class FName                             NewSlotName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UClass*                           TestedDataSource                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   PreferNewOne                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_DiveHorizontal_C::IsNewBallInterceptionPreferred(const struct FBallInterceptionPointTargetData& BaseBallInterception, const struct FBallInterceptionPointTargetData& NewBallInterception, class FName NewSlotName, class UClass* TestedDataSource, bool* PreferNewOne)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "IsNewBallInterceptionPreferred");

	Params::GA_DiveHorizontal_C_IsNewBallInterceptionPreferred Parms{};

	Parms.BaseBallInterception = std::move(BaseBallInterception);
	Parms.NewBallInterception = std::move(NewBallInterception);
	Parms.NewSlotName = NewSlotName;
	Parms.TestedDataSource = TestedDataSource;

	UObject::ProcessEvent(Func, &Parms);

	if (PreferNewOne != nullptr)
		*PreferNewOne = Parms.PreferNewOne;
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.FillupTestedTargetDataSource
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::FillupTestedTargetDataSource()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "FillupTestedTargetDataSource");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.IsAimAssistActivated
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   IsDiveAimAssistActivated                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_DiveHorizontal_C::IsAimAssistActivated(bool* IsDiveAimAssistActivated)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "IsAimAssistActivated");

	Params::GA_DiveHorizontal_C_IsAimAssistActivated Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (IsDiveAimAssistActivated != nullptr)
		*IsDiveAimAssistActivated = Parms.IsDiveAimAssistActivated;
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.ProcessPredictionData
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayAbilityTargetDataHandle&PredictionTargetData                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// struct FAnimSequencePickerInstance*     AnimSequencePicker                                     (Parm, OutParm, ContainsInstancedReference)
// class UBasicMontagePlayerConfiguration**Config                                                 (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// double*                                 TargetTime                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   IsPredictionValid                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_DiveHorizontal_C::ProcessPredictionData(const struct FGameplayAbilityTargetDataHandle& PredictionTargetData, struct FAnimSequencePickerInstance* AnimSequencePicker, class UBasicMontagePlayerConfiguration** Config, double* TargetTime, bool* IsPredictionValid)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "ProcessPredictionData");

	Params::GA_DiveHorizontal_C_ProcessPredictionData Parms{};

	Parms.PredictionTargetData = std::move(PredictionTargetData);

	UObject::ProcessEvent(Func, &Parms);

	if (AnimSequencePicker != nullptr)
		*AnimSequencePicker = std::move(Parms.AnimSequencePicker);

	if (Config != nullptr)
		*Config = Parms.Config;

	if (TargetTime != nullptr)
		*TargetTime = Parms.TargetTime;

	if (IsPredictionValid != nullptr)
		*IsPredictionValid = Parms.IsPredictionValid;
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.FindBallInterceptionTargetData
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayAbilityTargetDataHandle&_context                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// TSubclassOf<class UTargetDatasource>    TestedDataSource                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
// struct FBallInterceptionPointTargetData*ResultBestTarget                                       (Parm, OutParm)
// class FName*                            ResultSlotName                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EDiveDetectionCase*                     Array_Element_Case                                     (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSlotAnimSequencePlayInfos*      ResultSlotAnimSequencePlayInfo                         (Parm, OutParm)

void UGA_DiveHorizontal_C::FindBallInterceptionTargetData(const struct FGameplayAbilityTargetDataHandle& _context, TSubclassOf<class UTargetDatasource> TestedDataSource, struct FBallInterceptionPointTargetData* ResultBestTarget, class FName* ResultSlotName, EDiveDetectionCase* Array_Element_Case, struct FSlotAnimSequencePlayInfos* ResultSlotAnimSequencePlayInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "FindBallInterceptionTargetData");

	Params::GA_DiveHorizontal_C_FindBallInterceptionTargetData Parms{};

	Parms._context = std::move(_context);
	Parms.TestedDataSource = TestedDataSource;

	UObject::ProcessEvent(Func, &Parms);

	if (ResultBestTarget != nullptr)
		*ResultBestTarget = std::move(Parms.ResultBestTarget);

	if (ResultSlotName != nullptr)
		*ResultSlotName = Parms.ResultSlotName;

	if (Array_Element_Case != nullptr)
		*Array_Element_Case = Parms.Array_Element_Case;

	if (ResultSlotAnimSequencePlayInfo != nullptr)
		*ResultSlotAnimSequencePlayInfo = std::move(Parms.ResultSlotAnimSequencePlayInfo);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.InitializeBuildupInitialTargetDatas
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::InitializeBuildupInitialTargetDatas()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "InitializeBuildupInitialTargetDatas");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.Get Reoriented Input Target Data
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FInputGameplayAbilityTargetData&InInputTargetData                                      (BlueprintVisible, BlueprintReadOnly, Parm)
// const struct FBallInterceptionPointTargetData&InBallInterceptionTargetData                           (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FInputGameplayAbilityTargetData* ReorientedInputTargetData                              (Parm, OutParm)

void UGA_DiveHorizontal_C::Get_Reoriented_Input_Target_Data(const struct FInputGameplayAbilityTargetData& InInputTargetData, const struct FBallInterceptionPointTargetData& InBallInterceptionTargetData, struct FInputGameplayAbilityTargetData* ReorientedInputTargetData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "Get Reoriented Input Target Data");

	Params::GA_DiveHorizontal_C_Get_Reoriented_Input_Target_Data Parms{};

	Parms.InInputTargetData = std::move(InInputTargetData);
	Parms.InBallInterceptionTargetData = std::move(InBallInterceptionTargetData);

	UObject::ProcessEvent(Func, &Parms);

	if (ReorientedInputTargetData != nullptr)
		*ReorientedInputTargetData = std::move(Parms.ReorientedInputTargetData);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.DebugPredictionBallInterception
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayAbilityTargetDataHandle&_context                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UGA_DiveHorizontal_C::DebugPredictionBallInterception(const struct FGameplayAbilityTargetDataHandle& _context)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "DebugPredictionBallInterception");

	Params::GA_DiveHorizontal_C_DebugPredictionBallInterception Parms{};

	Parms._context = std::move(_context);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.DebugPredictionSyncTime
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPendingHit&               PendingHit                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void UGA_DiveHorizontal_C::DebugPredictionSyncTime(const struct FPendingHit& PendingHit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "DebugPredictionSyncTime");

	Params::GA_DiveHorizontal_C_DebugPredictionSyncTime Parms{};

	Parms.PendingHit = std::move(PendingHit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.OnStateInterrupted_464AA855450252AFA82A34B0051DDF1F
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::OnStateInterrupted_464AA855450252AFA82A34B0051DDF1F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "OnStateInterrupted_464AA855450252AFA82A34B0051DDF1F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.OnStateEnded_464AA855450252AFA82A34B0051DDF1F
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::OnStateEnded_464AA855450252AFA82A34B0051DDF1F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "OnStateEnded_464AA855450252AFA82A34B0051DDF1F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.OnStateInterrupted_3D54D3FA445E84FE865A0FAD4BC25E45
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::OnStateInterrupted_3D54D3FA445E84FE865A0FAD4BC25E45()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "OnStateInterrupted_3D54D3FA445E84FE865A0FAD4BC25E45");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.OnStateEnded_3D54D3FA445E84FE865A0FAD4BC25E45
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::OnStateEnded_3D54D3FA445E84FE865A0FAD4BC25E45()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "OnStateEnded_3D54D3FA445E84FE865A0FAD4BC25E45");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.m_BuildClientHitboxPayload_656DAED34DB820B9A83043834CAFDEAD
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPendingHit&               _hit                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// const struct FGameplayAbilityTargetDataHandle&_context                                               (BlueprintVisible, BlueprintReadOnly, Parm)
// class UAbilityTask_HandleHitboxBase*    _payloadTarget                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_DiveHorizontal_C::m_BuildClientHitboxPayload_656DAED34DB820B9A83043834CAFDEAD(const struct FPendingHit& _hit, const struct FGameplayAbilityTargetDataHandle& _context, class UAbilityTask_HandleHitboxBase* _payloadTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "m_BuildClientHitboxPayload_656DAED34DB820B9A83043834CAFDEAD");

	Params::GA_DiveHorizontal_C_m_BuildClientHitboxPayload_656DAED34DB820B9A83043834CAFDEAD Parms{};

	Parms._hit = std::move(_hit);
	Parms._context = std::move(_context);
	Parms._payloadTarget = _payloadTarget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.m_OnHitRejected_656DAED34DB820B9A83043834CAFDEAD
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPendingHit&               _hit                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// const struct FGameplayAbilityTargetDataHandle&_context                                               (BlueprintVisible, BlueprintReadOnly, Parm)
// class UAbilityTask_HandleHitboxBase*    _payloadTarget                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_DiveHorizontal_C::m_OnHitRejected_656DAED34DB820B9A83043834CAFDEAD(const struct FPendingHit& _hit, const struct FGameplayAbilityTargetDataHandle& _context, class UAbilityTask_HandleHitboxBase* _payloadTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "m_OnHitRejected_656DAED34DB820B9A83043834CAFDEAD");

	Params::GA_DiveHorizontal_C_m_OnHitRejected_656DAED34DB820B9A83043834CAFDEAD Parms{};

	Parms._hit = std::move(_hit);
	Parms._context = std::move(_context);
	Parms._payloadTarget = _payloadTarget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.m_OnHitRecovery_656DAED34DB820B9A83043834CAFDEAD
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPendingHit&               _hit                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// const struct FGameplayAbilityTargetDataHandle&_context                                               (BlueprintVisible, BlueprintReadOnly, Parm)
// class UAbilityTask_HandleHitboxBase*    _payloadTarget                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_DiveHorizontal_C::m_OnHitRecovery_656DAED34DB820B9A83043834CAFDEAD(const struct FPendingHit& _hit, const struct FGameplayAbilityTargetDataHandle& _context, class UAbilityTask_HandleHitboxBase* _payloadTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "m_OnHitRecovery_656DAED34DB820B9A83043834CAFDEAD");

	Params::GA_DiveHorizontal_C_m_OnHitRecovery_656DAED34DB820B9A83043834CAFDEAD Parms{};

	Parms._hit = std::move(_hit);
	Parms._context = std::move(_context);
	Parms._payloadTarget = _payloadTarget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.m_OnHitValidated_656DAED34DB820B9A83043834CAFDEAD
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPendingHit&               _hit                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// const struct FGameplayAbilityTargetDataHandle&_context                                               (BlueprintVisible, BlueprintReadOnly, Parm)
// class UAbilityTask_HandleHitboxBase*    _payloadTarget                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_DiveHorizontal_C::m_OnHitValidated_656DAED34DB820B9A83043834CAFDEAD(const struct FPendingHit& _hit, const struct FGameplayAbilityTargetDataHandle& _context, class UAbilityTask_HandleHitboxBase* _payloadTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "m_OnHitValidated_656DAED34DB820B9A83043834CAFDEAD");

	Params::GA_DiveHorizontal_C_m_OnHitValidated_656DAED34DB820B9A83043834CAFDEAD Parms{};

	Parms._hit = std::move(_hit);
	Parms._context = std::move(_context);
	Parms._payloadTarget = _payloadTarget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.m_OnHit_656DAED34DB820B9A83043834CAFDEAD
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPendingHit&               _hit                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// const struct FGameplayAbilityTargetDataHandle&_context                                               (BlueprintVisible, BlueprintReadOnly, Parm)
// class UAbilityTask_HandleHitboxBase*    _payloadTarget                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_DiveHorizontal_C::m_OnHit_656DAED34DB820B9A83043834CAFDEAD(const struct FPendingHit& _hit, const struct FGameplayAbilityTargetDataHandle& _context, class UAbilityTask_HandleHitboxBase* _payloadTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "m_OnHit_656DAED34DB820B9A83043834CAFDEAD");

	Params::GA_DiveHorizontal_C_m_OnHit_656DAED34DB820B9A83043834CAFDEAD Parms{};

	Parms._hit = std::move(_hit);
	Parms._context = std::move(_context);
	Parms._payloadTarget = _payloadTarget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.m_OnMiss_656DAED34DB820B9A83043834CAFDEAD
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPendingHit&               _hit                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// const struct FGameplayAbilityTargetDataHandle&_context                                               (BlueprintVisible, BlueprintReadOnly, Parm)
// class UAbilityTask_HandleHitboxBase*    _payloadTarget                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UGA_DiveHorizontal_C::m_OnMiss_656DAED34DB820B9A83043834CAFDEAD(const struct FPendingHit& _hit, const struct FGameplayAbilityTargetDataHandle& _context, class UAbilityTask_HandleHitboxBase* _payloadTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "m_OnMiss_656DAED34DB820B9A83043834CAFDEAD");

	Params::GA_DiveHorizontal_C_m_OnMiss_656DAED34DB820B9A83043834CAFDEAD Parms{};

	Parms._hit = std::move(_hit);
	Parms._context = std::move(_context);
	Parms._payloadTarget = _payloadTarget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.OnSync_1226E57048906756E71FC3B067BE79F4
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::OnSync_1226E57048906756E71FC3B067BE79F4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "OnSync_1226E57048906756E71FC3B067BE79F4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.OnHitProjectionFailed_04DCB01C4E9FFC1D6148A881F590F2A4
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::OnHitProjectionFailed_04DCB01C4E9FFC1D6148A881F590F2A4()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "OnHitProjectionFailed_04DCB01C4E9FFC1D6148A881F590F2A4");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.OnHitPredicted_04DCB01C4E9FFC1D6148A881F590F2A4
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayAbilityTargetDataHandle&Data                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UGA_DiveHorizontal_C::OnHitPredicted_04DCB01C4E9FFC1D6148A881F590F2A4(const struct FGameplayAbilityTargetDataHandle& Data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "OnHitPredicted_04DCB01C4E9FFC1D6148A881F590F2A4");

	Params::GA_DiveHorizontal_C_OnHitPredicted_04DCB01C4E9FFC1D6148A881F590F2A4 Parms{};

	Parms.Data = std::move(Data);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.OnCancelled_08FA0C824073AFBA56CC97BB5C811152
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::OnCancelled_08FA0C824073AFBA56CC97BB5C811152()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "OnCancelled_08FA0C824073AFBA56CC97BB5C811152");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.OnInterrupted_08FA0C824073AFBA56CC97BB5C811152
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::OnInterrupted_08FA0C824073AFBA56CC97BB5C811152()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "OnInterrupted_08FA0C824073AFBA56CC97BB5C811152");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.OnBlendOut_08FA0C824073AFBA56CC97BB5C811152
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::OnBlendOut_08FA0C824073AFBA56CC97BB5C811152()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "OnBlendOut_08FA0C824073AFBA56CC97BB5C811152");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.OnBlendedIn_08FA0C824073AFBA56CC97BB5C811152
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::OnBlendedIn_08FA0C824073AFBA56CC97BB5C811152()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "OnBlendedIn_08FA0C824073AFBA56CC97BB5C811152");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.OnCompleted_08FA0C824073AFBA56CC97BB5C811152
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::OnCompleted_08FA0C824073AFBA56CC97BB5C811152()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "OnCompleted_08FA0C824073AFBA56CC97BB5C811152");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.m_OnValidNullMontageChosen_08FA0C824073AFBA56CC97BB5C811152
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::m_OnValidNullMontageChosen_08FA0C824073AFBA56CC97BB5C811152()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "m_OnValidNullMontageChosen_08FA0C824073AFBA56CC97BB5C811152");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.m_OnMoveInterrupt_08FA0C824073AFBA56CC97BB5C811152
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::m_OnMoveInterrupt_08FA0C824073AFBA56CC97BB5C811152()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "m_OnMoveInterrupt_08FA0C824073AFBA56CC97BB5C811152");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.m_OnCanMoveInterrupt_08FA0C824073AFBA56CC97BB5C811152
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::m_OnCanMoveInterrupt_08FA0C824073AFBA56CC97BB5C811152()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "m_OnCanMoveInterrupt_08FA0C824073AFBA56CC97BB5C811152");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.OnCancelled_C8C22E1843BE260AC39799B682ABEF38
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::OnCancelled_C8C22E1843BE260AC39799B682ABEF38()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "OnCancelled_C8C22E1843BE260AC39799B682ABEF38");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.OnInterrupted_C8C22E1843BE260AC39799B682ABEF38
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::OnInterrupted_C8C22E1843BE260AC39799B682ABEF38()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "OnInterrupted_C8C22E1843BE260AC39799B682ABEF38");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.OnBlendOut_C8C22E1843BE260AC39799B682ABEF38
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::OnBlendOut_C8C22E1843BE260AC39799B682ABEF38()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "OnBlendOut_C8C22E1843BE260AC39799B682ABEF38");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.OnBlendedIn_C8C22E1843BE260AC39799B682ABEF38
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::OnBlendedIn_C8C22E1843BE260AC39799B682ABEF38()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "OnBlendedIn_C8C22E1843BE260AC39799B682ABEF38");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.OnCompleted_C8C22E1843BE260AC39799B682ABEF38
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::OnCompleted_C8C22E1843BE260AC39799B682ABEF38()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "OnCompleted_C8C22E1843BE260AC39799B682ABEF38");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.m_OnValidNullMontageChosen_C8C22E1843BE260AC39799B682ABEF38
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::m_OnValidNullMontageChosen_C8C22E1843BE260AC39799B682ABEF38()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "m_OnValidNullMontageChosen_C8C22E1843BE260AC39799B682ABEF38");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.m_OnMoveInterrupt_C8C22E1843BE260AC39799B682ABEF38
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::m_OnMoveInterrupt_C8C22E1843BE260AC39799B682ABEF38()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "m_OnMoveInterrupt_C8C22E1843BE260AC39799B682ABEF38");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.m_OnCanMoveInterrupt_C8C22E1843BE260AC39799B682ABEF38
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::m_OnCanMoveInterrupt_C8C22E1843BE260AC39799B682ABEF38()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "m_OnCanMoveInterrupt_C8C22E1843BE260AC39799B682ABEF38");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.DebugSpeed
// (BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_C::DebugSpeed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "DebugSpeed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.GetDiveTargetData
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    bInBuildPayload                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FGameplayAbilityTargetDataHandle ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FGameplayAbilityTargetDataHandle UGA_DiveHorizontal_C::GetDiveTargetData(bool bInBuildPayload) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "GetDiveTargetData");

	Params::GA_DiveHorizontal_C_GetDiveTargetData Parms{};

	Parms.bInBuildPayload = bInBuildPayload;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.CanConsiderDiveUp
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UGA_DiveHorizontal_C::CanConsiderDiveUp() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "CanConsiderDiveUp");

	Params::GA_DiveHorizontal_C_CanConsiderDiveUp Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.LogAnimSlot
// (Public, BlueprintCallable, BlueprintEvent, Const)

void UGA_DiveHorizontal_C::LogAnimSlot() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "LogAnimSlot");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.SelectOnHitParameters
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// TSubclassOf<class UAnimSequencePickerSlotContainer>*AnimPicker                                             (Parm, OutParm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
// class UBasicMontagePlayerConfiguration**AnimConfiguration                                      (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FGameplayTag*                    OnHitGameplayCueTag                                    (Parm, OutParm, NoDestructor, HasGetValueTypeHash)

void UGA_DiveHorizontal_C::SelectOnHitParameters(const struct FGameplayTag& Tag, TSubclassOf<class UAnimSequencePickerSlotContainer>* AnimPicker, class UBasicMontagePlayerConfiguration** AnimConfiguration, struct FGameplayTag* OnHitGameplayCueTag) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "SelectOnHitParameters");

	Params::GA_DiveHorizontal_C_SelectOnHitParameters Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);

	if (AnimPicker != nullptr)
		*AnimPicker = Parms.AnimPicker;

	if (AnimConfiguration != nullptr)
		*AnimConfiguration = Parms.AnimConfiguration;

	if (OnHitGameplayCueTag != nullptr)
		*OnHitGameplayCueTag = std::move(Parms.OnHitGameplayCueTag);
}


// Function GA_DiveHorizontal.GA_DiveHorizontal_C.SelectInitialMontagePlayerConfiguration
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// const struct FGameplayAbilityTargetDataHandle&_in                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UBasicMontagePlayerConfiguration* ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
// class UClass**                          AnimMontagePicker                                      (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

class UBasicMontagePlayerConfiguration* UGA_DiveHorizontal_C::SelectInitialMontagePlayerConfiguration(const struct FGameplayAbilityTargetDataHandle& _in, class UClass** AnimMontagePicker) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_C", "SelectInitialMontagePlayerConfiguration");

	Params::GA_DiveHorizontal_C_SelectInitialMontagePlayerConfiguration Parms{};

	Parms._in = std::move(_in);

	UObject::ProcessEvent(Func, &Parms);

	if (AnimMontagePicker != nullptr)
		*AnimMontagePicker = Parms.AnimMontagePicker;

	return Parms.ReturnValue;
}

}

