#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_DiveHorizontal_Field

#include "Basic.hpp"

#include "GA_DiveHorizontal_Field_classes.hpp"
#include "GA_DiveHorizontal_Field_parameters.hpp"


namespace SDK
{

// Function GA_DiveHorizontal_Field.GA_DiveHorizontal_Field_C.ExecuteUbergraph_GA_DiveHorizontal_Field
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_DiveHorizontal_Field_C::ExecuteUbergraph_GA_DiveHorizontal_Field(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_Field_C", "ExecuteUbergraph_GA_DiveHorizontal_Field");

	Params::GA_DiveHorizontal_Field_C_ExecuteUbergraph_GA_DiveHorizontal_Field Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_DiveHorizontal_Field.GA_DiveHorizontal_Field_C.InitializeBuildupInitialTargetDatas
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_Field_C::InitializeBuildupInitialTargetDatas()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_Field_C", "InitializeBuildupInitialTargetDatas");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal_Field.GA_DiveHorizontal_Field_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_DiveHorizontal_Field_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_Field_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal_Field.GA_DiveHorizontal_Field_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_DiveHorizontal_Field_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_Field_C", "K2_OnEndAbility");

	Params::GA_DiveHorizontal_Field_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_DiveHorizontal_Field.GA_DiveHorizontal_Field_C.Reset Buildup Vars
// (Public, BlueprintCallable, BlueprintEvent)

void UGA_DiveHorizontal_Field_C::Reset_Buildup_Vars()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_Field_C", "Reset Buildup Vars");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DiveHorizontal_Field.GA_DiveHorizontal_Field_C.SelectInitialMontagePlayerConfiguration
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// const struct FGameplayAbilityTargetDataHandle&_in                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class UBasicMontagePlayerConfiguration* ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
// class UClass**                          AnimMontagePicker                                      (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

class UBasicMontagePlayerConfiguration* UGA_DiveHorizontal_Field_C::SelectInitialMontagePlayerConfiguration(const struct FGameplayAbilityTargetDataHandle& _in, class UClass** AnimMontagePicker) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DiveHorizontal_Field_C", "SelectInitialMontagePlayerConfiguration");

	Params::GA_DiveHorizontal_Field_C_SelectInitialMontagePlayerConfiguration Parms{};

	Parms._in = std::move(_in);

	UObject::ProcessEvent(Func, &Parms);

	if (AnimMontagePicker != nullptr)
		*AnimMontagePicker = Parms.AnimMontagePicker;

	return Parms.ReturnValue;
}

}

