#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_PlayAnimEvent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Runtime_classes.hpp"
#include "SCCore_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_PlayAnimEvent.GA_PlayAnimEvent_C
// 0x0008 (0x0660 - 0x0658)
class UGA_PlayAnimEvent_C : public URuntimeGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0658(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void BPE_BuildPayload();
	void ExecuteUbergraph_GA_PlayAnimEvent(int32 EntryPoint);
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);
	void m_OnCanMoveInterrupt_3B998BDF42FBED59F909049636C76703();
	void m_OnMoveInterrupt_3B998BDF42FBED59F909049636C76703();
	void m_OnValidNullMontageChosen_3B998BDF42FBED59F909049636C76703();
	void OnBlendedIn_3B998BDF42FBED59F909049636C76703();
	void OnBlendOut_3B998BDF42FBED59F909049636C76703();
	void OnCancelled_3B998BDF42FBED59F909049636C76703();
	void OnCompleted_3B998BDF42FBED59F909049636C76703();
	void OnInterrupted_3B998BDF42FBED59F909049636C76703();

	void GetAnimSequencePicker(class UClass** AsAnim_Sequence_Picker) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GA_PlayAnimEvent_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GA_PlayAnimEvent_C")
	}
	static class UGA_PlayAnimEvent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_PlayAnimEvent_C>();
	}
};
DUMPER7_ASSERTS_UGA_PlayAnimEvent_C;

}

