#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Shoot

#include "Basic.hpp"

#include "GA_Shoot_classes.hpp"
#include "GA_Shoot_parameters.hpp"


namespace SDK
{

// Function GA_Shoot.GA_Shoot_C.BPE_BuildPayload
// (Event, Public, BlueprintEvent)

void UGA_Shoot_C::BPE_BuildPayload()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "BPE_BuildPayload");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.ExecuteUbergraph_GA_Shoot
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Shoot_C::ExecuteUbergraph_GA_Shoot(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "ExecuteUbergraph_GA_Shoot");

	Params::GA_Shoot_C_ExecuteUbergraph_GA_Shoot Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Shoot.GA_Shoot_C.InitOverrideComputationForKeyBoard
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsKeyBoardController                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   LockGameOption                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Shoot_C::InitOverrideComputationForKeyBoard(bool IsKeyBoardController, int32 LockGameOption)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "InitOverrideComputationForKeyBoard");

	Params::GA_Shoot_C_InitOverrideComputationForKeyBoard Parms{};

	Parms.IsKeyBoardController = IsKeyBoardController;
	Parms.LockGameOption = LockGameOption;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Shoot.GA_Shoot_C.InitTargetDatasAndConfiguration
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::InitTargetDatasAndConfiguration()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "InitTargetDatasAndConfiguration");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.K2_ActivateAbilityFromEvent
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FGameplayEventData&        EventData                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UGA_Shoot_C::K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "K2_ActivateAbilityFromEvent");

	Params::GA_Shoot_C_K2_ActivateAbilityFromEvent Parms{};

	Parms.EventData = std::move(EventData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Shoot.GA_Shoot_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_Shoot_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "K2_OnEndAbility");

	Params::GA_Shoot_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Shoot.GA_Shoot_C.m_BuildClientPayload_2AA78B3F4B3D61AEE19D01A27D33DB17
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayAbilityTargetDataHandle&Data                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UGA_Shoot_C::m_BuildClientPayload_2AA78B3F4B3D61AEE19D01A27D33DB17(const struct FGameplayAbilityTargetDataHandle& Data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "m_BuildClientPayload_2AA78B3F4B3D61AEE19D01A27D33DB17");

	Params::GA_Shoot_C_m_BuildClientPayload_2AA78B3F4B3D61AEE19D01A27D33DB17 Parms{};

	Parms.Data = std::move(Data);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Shoot.GA_Shoot_C.m_OnCanMoveInterrupt_8E40574B443096550598C2A0EA97F952
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::m_OnCanMoveInterrupt_8E40574B443096550598C2A0EA97F952()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "m_OnCanMoveInterrupt_8E40574B443096550598C2A0EA97F952");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.m_OnCanMoveInterrupt_9EDBEC40434FA9E15BAA60B5949DB009
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::m_OnCanMoveInterrupt_9EDBEC40434FA9E15BAA60B5949DB009()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "m_OnCanMoveInterrupt_9EDBEC40434FA9E15BAA60B5949DB009");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.m_OnCanMoveInterrupt_B4A8C37944A1E2CAB7FA8494732484D3
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::m_OnCanMoveInterrupt_B4A8C37944A1E2CAB7FA8494732484D3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "m_OnCanMoveInterrupt_B4A8C37944A1E2CAB7FA8494732484D3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.m_OnMoveInterrupt_8E40574B443096550598C2A0EA97F952
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::m_OnMoveInterrupt_8E40574B443096550598C2A0EA97F952()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "m_OnMoveInterrupt_8E40574B443096550598C2A0EA97F952");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.m_OnMoveInterrupt_9EDBEC40434FA9E15BAA60B5949DB009
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::m_OnMoveInterrupt_9EDBEC40434FA9E15BAA60B5949DB009()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "m_OnMoveInterrupt_9EDBEC40434FA9E15BAA60B5949DB009");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.m_OnMoveInterrupt_B4A8C37944A1E2CAB7FA8494732484D3
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::m_OnMoveInterrupt_B4A8C37944A1E2CAB7FA8494732484D3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "m_OnMoveInterrupt_B4A8C37944A1E2CAB7FA8494732484D3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.m_OnShoot_29D215A544B8BB6AF5A2D18A493A7141
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::m_OnShoot_29D215A544B8BB6AF5A2D18A493A7141()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "m_OnShoot_29D215A544B8BB6AF5A2D18A493A7141");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.m_OnShootCanceled_29D215A544B8BB6AF5A2D18A493A7141
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::m_OnShootCanceled_29D215A544B8BB6AF5A2D18A493A7141()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "m_OnShootCanceled_29D215A544B8BB6AF5A2D18A493A7141");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.m_OnValidNullMontageChosen_8E40574B443096550598C2A0EA97F952
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::m_OnValidNullMontageChosen_8E40574B443096550598C2A0EA97F952()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "m_OnValidNullMontageChosen_8E40574B443096550598C2A0EA97F952");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.m_OnValidNullMontageChosen_9EDBEC40434FA9E15BAA60B5949DB009
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::m_OnValidNullMontageChosen_9EDBEC40434FA9E15BAA60B5949DB009()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "m_OnValidNullMontageChosen_9EDBEC40434FA9E15BAA60B5949DB009");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.m_OnValidNullMontageChosen_B4A8C37944A1E2CAB7FA8494732484D3
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::m_OnValidNullMontageChosen_B4A8C37944A1E2CAB7FA8494732484D3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "m_OnValidNullMontageChosen_B4A8C37944A1E2CAB7FA8494732484D3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.OnBlendedIn_8E40574B443096550598C2A0EA97F952
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::OnBlendedIn_8E40574B443096550598C2A0EA97F952()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "OnBlendedIn_8E40574B443096550598C2A0EA97F952");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.OnBlendedIn_9EDBEC40434FA9E15BAA60B5949DB009
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::OnBlendedIn_9EDBEC40434FA9E15BAA60B5949DB009()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "OnBlendedIn_9EDBEC40434FA9E15BAA60B5949DB009");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.OnBlendedIn_B4A8C37944A1E2CAB7FA8494732484D3
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::OnBlendedIn_B4A8C37944A1E2CAB7FA8494732484D3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "OnBlendedIn_B4A8C37944A1E2CAB7FA8494732484D3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.OnBlendOut_8E40574B443096550598C2A0EA97F952
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::OnBlendOut_8E40574B443096550598C2A0EA97F952()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "OnBlendOut_8E40574B443096550598C2A0EA97F952");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.OnBlendOut_9EDBEC40434FA9E15BAA60B5949DB009
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::OnBlendOut_9EDBEC40434FA9E15BAA60B5949DB009()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "OnBlendOut_9EDBEC40434FA9E15BAA60B5949DB009");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.OnBlendOut_B4A8C37944A1E2CAB7FA8494732484D3
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::OnBlendOut_B4A8C37944A1E2CAB7FA8494732484D3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "OnBlendOut_B4A8C37944A1E2CAB7FA8494732484D3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.OnCancel_2AA78B3F4B3D61AEE19D01A27D33DB17
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayAbilityTargetDataHandle&Data                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UGA_Shoot_C::OnCancel_2AA78B3F4B3D61AEE19D01A27D33DB17(const struct FGameplayAbilityTargetDataHandle& Data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "OnCancel_2AA78B3F4B3D61AEE19D01A27D33DB17");

	Params::GA_Shoot_C_OnCancel_2AA78B3F4B3D61AEE19D01A27D33DB17 Parms{};

	Parms.Data = std::move(Data);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Shoot.GA_Shoot_C.OnCancelled_8E40574B443096550598C2A0EA97F952
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::OnCancelled_8E40574B443096550598C2A0EA97F952()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "OnCancelled_8E40574B443096550598C2A0EA97F952");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.OnCancelled_9EDBEC40434FA9E15BAA60B5949DB009
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::OnCancelled_9EDBEC40434FA9E15BAA60B5949DB009()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "OnCancelled_9EDBEC40434FA9E15BAA60B5949DB009");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.OnCancelled_B4A8C37944A1E2CAB7FA8494732484D3
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::OnCancelled_B4A8C37944A1E2CAB7FA8494732484D3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "OnCancelled_B4A8C37944A1E2CAB7FA8494732484D3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.OnCompleted_8E40574B443096550598C2A0EA97F952
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::OnCompleted_8E40574B443096550598C2A0EA97F952()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "OnCompleted_8E40574B443096550598C2A0EA97F952");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.OnCompleted_9EDBEC40434FA9E15BAA60B5949DB009
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::OnCompleted_9EDBEC40434FA9E15BAA60B5949DB009()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "OnCompleted_9EDBEC40434FA9E15BAA60B5949DB009");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.OnCompleted_B4A8C37944A1E2CAB7FA8494732484D3
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::OnCompleted_B4A8C37944A1E2CAB7FA8494732484D3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "OnCompleted_B4A8C37944A1E2CAB7FA8494732484D3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.OnInterrupted_8E40574B443096550598C2A0EA97F952
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::OnInterrupted_8E40574B443096550598C2A0EA97F952()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "OnInterrupted_8E40574B443096550598C2A0EA97F952");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.OnInterrupted_9EDBEC40434FA9E15BAA60B5949DB009
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::OnInterrupted_9EDBEC40434FA9E15BAA60B5949DB009()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "OnInterrupted_9EDBEC40434FA9E15BAA60B5949DB009");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.OnInterrupted_B4A8C37944A1E2CAB7FA8494732484D3
// (BlueprintCallable, BlueprintEvent)

void UGA_Shoot_C::OnInterrupted_B4A8C37944A1E2CAB7FA8494732484D3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "OnInterrupted_B4A8C37944A1E2CAB7FA8494732484D3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_Shoot.GA_Shoot_C.OnSync_2AA78B3F4B3D61AEE19D01A27D33DB17
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayAbilityTargetDataHandle&Data                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UGA_Shoot_C::OnSync_2AA78B3F4B3D61AEE19D01A27D33DB17(const struct FGameplayAbilityTargetDataHandle& Data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "OnSync_2AA78B3F4B3D61AEE19D01A27D33DB17");

	Params::GA_Shoot_C_OnSync_2AA78B3F4B3D61AEE19D01A27D33DB17 Parms{};

	Parms.Data = std::move(Data);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Shoot.GA_Shoot_C.OnTimeOut_2AA78B3F4B3D61AEE19D01A27D33DB17
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayAbilityTargetDataHandle&Data                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UGA_Shoot_C::OnTimeOut_2AA78B3F4B3D61AEE19D01A27D33DB17(const struct FGameplayAbilityTargetDataHandle& Data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "OnTimeOut_2AA78B3F4B3D61AEE19D01A27D33DB17");

	Params::GA_Shoot_C_OnTimeOut_2AA78B3F4B3D61AEE19D01A27D33DB17 Parms{};

	Parms.Data = std::move(Data);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Shoot.GA_Shoot_C.UpdateShootParamsTags
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FShootParams&              in_ShootParams                                         (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FShootParams*                    out_ShootParams                                        (Parm, OutParm)

void UGA_Shoot_C::UpdateShootParamsTags(const struct FShootParams& in_ShootParams, struct FShootParams* out_ShootParams)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "UpdateShootParamsTags");

	Params::GA_Shoot_C_UpdateShootParamsTags Parms{};

	Parms.in_ShootParams = std::move(in_ShootParams);

	UObject::ProcessEvent(Func, &Parms);

	if (out_ShootParams != nullptr)
		*out_ShootParams = std::move(Parms.out_ShootParams);
}


// Function GA_Shoot.GA_Shoot_C.UpdateShootPrep
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayAbilityTargetDataHandle&_context                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UGA_Shoot_C::UpdateShootPrep(const struct FGameplayAbilityTargetDataHandle& _context)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "UpdateShootPrep");

	Params::GA_Shoot_C_UpdateShootPrep Parms{};

	Parms._context = std::move(_context);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_Shoot.GA_Shoot_C.DefineShootType
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// const struct FShootParams&              ShootParams_0                                          (BlueprintVisible, BlueprintReadOnly, Parm)
// struct FGameplayTag*                    ShootType                                              (Parm, OutParm, NoDestructor, HasGetValueTypeHash)

void UGA_Shoot_C::DefineShootType(const struct FShootParams& ShootParams_0, struct FGameplayTag* ShootType) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "DefineShootType");

	Params::GA_Shoot_C_DefineShootType Parms{};

	Parms.ShootParams_0 = std::move(ShootParams_0);

	UObject::ProcessEvent(Func, &Parms);

	if (ShootType != nullptr)
		*ShootType = std::move(Parms.ShootType);
}


// Function GA_Shoot.GA_Shoot_C.SelectFinalAnimPicker
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// const struct FShootParams&              ShootParams_0                                          (BlueprintVisible, BlueprintReadOnly, Parm)
// TSubclassOf<class UAnimSequencePickerSlotContainer>*Picker                                                 (Parm, OutParm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

void UGA_Shoot_C::SelectFinalAnimPicker(const struct FShootParams& ShootParams_0, TSubclassOf<class UAnimSequencePickerSlotContainer>* Picker) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_Shoot_C", "SelectFinalAnimPicker");

	Params::GA_Shoot_C_SelectFinalAnimPicker Parms{};

	Parms.ShootParams_0 = std::move(ShootParams_0);

	UObject::ProcessEvent(Func, &Parms);

	if (Picker != nullptr)
		*Picker = Parms.Picker;
}

}

