#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_VolleyTap

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Runtime_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "SCCore_structs.hpp"
#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK::Params
{

// Function GA_VolleyTap.GA_VolleyTap_C.ExecuteUbergraph_GA_VolleyTap
// 0x19E0 (0x19E0 - 0x0000)
struct GA_VolleyTap_C_ExecuteUbergraph_GA_VolleyTap final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x0014(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0024(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x0034(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_4;            // 0x0044(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_5;            // 0x0054(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_6;            // 0x0064(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_7;            // 0x0074(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_84[0x4];                                       // 0x0084(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayAbilityTargetDataHandle       K2Node_CustomEvent_Data_3;                         // 0x0088(0x0028)(ConstParm)
	TDelegate<void(const struct FGameplayAbilityTargetDataHandle& Data)> K2Node_CreateDelegate_OutputDelegate_8; // 0x00B0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayAbilityTargetDataHandle       K2Node_CustomEvent_Data_2;                         // 0x00C0(0x0028)(ConstParm)
	TDelegate<void(const struct FGameplayAbilityTargetDataHandle& Data)> K2Node_CreateDelegate_OutputDelegate_9; // 0x00E8(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayAbilityTargetDataHandle       K2Node_CustomEvent_Data_1;                         // 0x00F8(0x0028)(ConstParm)
	TDelegate<void(const struct FGameplayAbilityTargetDataHandle& Data)> K2Node_CreateDelegate_OutputDelegate_10; // 0x0120(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayAbilityTargetDataHandle       K2Node_CustomEvent_Data;                           // 0x0130(0x0028)(ConstParm)
	TDelegate<void(const struct FGameplayAbilityTargetDataHandle& Data)> K2Node_CreateDelegate_OutputDelegate_11; // 0x0158(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayAbilityTargetDataHandle       Temp_struct_Variable;                              // 0x0168(0x0028)()
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_12;           // 0x0190(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FShootParamsTargetData                 CallFunc_GetTargetDataPure__outData;               // 0x01A0(0x0118)()
	bool                                          CallFunc_GetTargetDataPure_ReturnValue;            // 0x02B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B9[0x7];                                      // 0x02B9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayAbilityTargetDataHandle       CallFunc_GetPlayerContext_PlayerContext;           // 0x02C0(0x0028)()
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_13;           // 0x02E8(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAbilityTask_SCStartAbilityState*       CallFunc_BPF_StartAbilityState_ReturnValue;        // 0x02F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_14;           // 0x0300(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0310(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_311[0x3];                                      // 0x0311(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_15;           // 0x0314(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_324[0x4];                                      // 0x0324(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOverrideDirectionComputationTargetData K2Node_MakeStruct_OverrideDirectionComputationTargetData; // 0x0328(0x0018)()
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0340(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_341[0x7];                                      // 0x0341(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayAbilityTargetDataHandle       CallFunc_MakeTargetDataHandle__outHandle;          // 0x0348(0x0028)()
	bool                                          CallFunc_HasRequestBeenGranted_ReturnValue;        // 0x0370(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasRequestBeenProcessed_ReturnValue;      // 0x0371(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_372[0x6];                                      // 0x0372(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOverrideDirectionComputationTargetData K2Node_MakeStruct_OverrideDirectionComputationTargetData_1; // 0x0378(0x0018)()
	struct FGameplayAbilityTargetDataHandle       CallFunc_MakeTargetDataHandle__outHandle_1;        // 0x0390(0x0028)()
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_16;           // 0x03B8(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_17;           // 0x03C8(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_18;           // 0x03D8(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwningActorFromActorInfo_ReturnValue;  // 0x03E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ARuntimeCharacter*                      K2Node_DynamicCast_AsRuntime_Character;            // 0x03F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x03F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BPF_SetBall_ReturnValue;                  // 0x03F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3FA[0x2];                                      // 0x03FA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FActiveGameplayEffectHandle            CallFunc_BP_ApplyGameplayEffectToOwner_ReturnValue; // 0x03FC(0x0008)(NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_19;           // 0x0404(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_20;           // 0x0414(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_424[0x4];                                      // 0x0424(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTargetDatasourceInstance              K2Node_MakeStruct_TargetDatasourceInstance;        // 0x0428(0x0048)(ContainsInstancedReference)
	struct FOnDemandTargetProvider                K2Node_MakeStruct_OnDemandTargetProvider;          // 0x0470(0x0058)(ContainsInstancedReference)
	uint8                                         Pad_4C8[0x8];                                      // 0x04C8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimSequencePlayInfos                 CallFunc_GetTargetDataPure__outData_1;             // 0x04D0(0x0130)()
	bool                                          CallFunc_GetTargetDataPure_ReturnValue_1;          // 0x0600(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_601[0x7];                                      // 0x0601(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwningActorFromActorInfo_ReturnValue_1; // 0x0608(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimSequenceBase*                      Temp_wildcard_Variable;                            // 0x0610(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_618[0x8];                                      // 0x0618(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimSequencePlayInfos                 CallFunc_GetTargetDataPure__outData_2;             // 0x0620(0x0130)()
	bool                                          CallFunc_GetTargetDataPure_ReturnValue_2;          // 0x0750(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0751(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_752[0x6];                                      // 0x0752(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNotifyEvent                       CallFunc_FindNotifyStateByClass__outFoundNotify;   // 0x0758(0x00B8)(ContainsInstancedReference)
	bool                                          CallFunc_FindNotifyStateByClass__bOutFound;        // 0x0810(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_811[0x7];                                      // 0x0811(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwningActorFromActorInfo_ReturnValue_2; // 0x0818(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ARuntimeCharacter*                      K2Node_DynamicCast_AsRuntime_Character_1;          // 0x0820(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0828(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_829[0x7];                                      // 0x0829(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwningActorFromActorInfo_ReturnValue_3; // 0x0830(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0838(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_839[0x7];                                      // 0x0839(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ARuntimeCharacter*                      K2Node_DynamicCast_AsRuntime_Character_2;          // 0x0840(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0848(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0849(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BPF_HasBall_ReturnValue;                  // 0x084A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BPF_SetBall_ReturnValue_1;                // 0x084B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x084C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_84D[0x3];                                      // 0x084D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FActiveGameplayEffectHandle            CallFunc_BP_ApplyGameplayEffectToOwner_ReturnValue_1; // 0x0850(0x0008)(NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_21;           // 0x0858(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAbilityTask_WaitDelay*                 CallFunc_WaitDelay_ReturnValue;                    // 0x0868(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0870(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_871[0x7];                                      // 0x0871(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAbilityTask_HandleGameplayCue*         Temp_wildcard_Variable_1;                          // 0x0878(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAbilityTask_HandleLooseGameplayTags*   Temp_wildcard_Variable_2;                          // 0x0880(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwningActorFromActorInfo_ReturnValue_4; // 0x0888(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayAbilityTargetDataHandle       CallFunc_MakeTargetDataHandle__outHandle_2;        // 0x0890(0x0028)()
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_22;           // 0x08B8(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  CallFunc_BPF_GetAbilityTags_ReturnValue;           // 0x08C8(0x0020)()
	struct FGameplayEffectContextHandle           CallFunc_BPF_MakeRuntimeGameplayEffectContextHandle__outHandle; // 0x08E8(0x0018)()
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_23;           // 0x0900(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAbilityTask_HandleGameplayCue*         CallFunc_BPF_HandleGameplayCue_ReturnValue;        // 0x0910(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x0918(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_919[0x7];                                      // 0x0919(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayAbilityTargetDataHandle       CallFunc_GetProvidedTargetData__outData;           // 0x0920(0x0028)()
	uint8                                         Pad_948[0x8];                                      // 0x0948(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FBallInterceptionPointTargetData       CallFunc_GetTargetDataPure__outData_3;             // 0x0950(0x0120)()
	bool                                          CallFunc_GetTargetDataPure_ReturnValue_3;          // 0x0A70(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A71[0x7];                                      // 0x0A71(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ARuntimeCharacter*                      CallFunc_BPF_GetRuntimeCharacter_ReturnValue;      // 0x0A78(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BreakTransform_Location;                  // 0x0A80(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_BreakTransform_Rotation;                  // 0x0A98(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_BreakTransform_Scale;                     // 0x0AB0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0AC8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTargetDatasourceInstance              K2Node_MakeStruct_TargetDatasourceInstance_1;      // 0x0AE0(0x0048)(ContainsInstancedReference)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x0B28(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FOnDemandTargetProvider                K2Node_MakeStruct_OnDemandTargetProvider_1;        // 0x0B40(0x0058)(ContainsInstancedReference)
	struct FRotator                               CallFunc_MakeRotFromX_ReturnValue;                 // 0x0B98(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class ARuntimeCharacter*                      CallFunc_BPF_GetRuntimeCharacter_ReturnValue_1;    // 0x0BB0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Roll;                        // 0x0BB8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Pitch;                       // 0x0BBC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakRotator_Yaw;                         // 0x0BC0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BC4[0x4];                                      // 0x0BC4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AController*                            CallFunc_GetController_ReturnValue;                // 0x0BC8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0BD0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class APlayerController*                      K2Node_DynamicCast_AsPlayer_Controller;            // 0x0BE8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0BF0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BF1[0x7];                                      // 0x0BF1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      K2Node_DynamicCast_AsPlayer_Controller_1;          // 0x0BF8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0C00(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C01[0x3];                                      // 0x0C01(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_24;           // 0x0C04(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C14[0x4];                                      // 0x0C14(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CallFunc_GetCameraRotation_ReturnValue;            // 0x0C18(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector                                CallFunc_GetForwardVector_ReturnValue;             // 0x0C30(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ARuntimeCharacter*                      CallFunc_BPF_GetRuntimeCharacter_ReturnValue_2;    // 0x0C48(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_25;           // 0x0C50(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_BPF_GetShootDirection_ReturnValue;        // 0x0C60(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_AngleBetweenVectorHorizontal_ReturnValue; // 0x0C78(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_RadiansToDegrees_ReturnValue;             // 0x0C80(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_26;           // 0x0C88(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Abs_ReturnValue;                          // 0x0C98(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_27;           // 0x0CA0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayAbilityTargetDataHandle       CallFunc_GetProvidedTargetData__outData_1;         // 0x0CB0(0x0028)()
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_28;           // 0x0CD8(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ARuntimeCharacter*                      CallFunc_BPF_GetRuntimeCharacter_ReturnValue_3;    // 0x0CE8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ARuntimeCharacter*                      CallFunc_BPF_GetRuntimeCharacter_ReturnValue_4;    // 0x0CF0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsBotControlled_ReturnValue;              // 0x0CF8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsBotControlled_ReturnValue_1;            // 0x0CF9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAbilityExecOrigin                            Temp_byte_Variable;                                // 0x0CFA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_CFB[0x5];                                      // 0x0CFB(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class URuntimeSaveSubsystem*                  CallFunc_GetLocalPlayerSubsystem_ReturnValue;      // 0x0D00(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x0D08(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D09[0x7];                                      // 0x0D09(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class URuntimeSaveSubsystem*                  CallFunc_GetLocalPlayerSubsystem_ReturnValue_1;    // 0x0D10(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EAbilityExecOrigin                            Temp_byte_Variable_1;                              // 0x0D18(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x0D19(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D1A[0x6];                                      // 0x0D1A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayAbilityTargetDataHandle       Temp_struct_Variable_1;                            // 0x0D20(0x0028)(ConstParm)
	struct FGameplayAbilityTargetDataHandle       CallFunc_GetProvidedTargetData__outData_2;         // 0x0D48(0x0028)()
	class UAbilityTask_WaitDelay*                 CallFunc_WaitDelay_ReturnValue_1;                  // 0x0D70(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ARuntimeCharacter*                      CallFunc_BPF_GetRuntimeCharacter_ReturnValue_5;    // 0x0D78(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AController*                            CallFunc_GetController_ReturnValue_1;              // 0x0D80(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsBotControlled_ReturnValue_2;            // 0x0D88(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D89[0x7];                                      // 0x0D89(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ASCBasePlayerController*                K2Node_DynamicCast_AsSCBase_Player_Controller;     // 0x0D90(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x0D98(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0D99(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BPF_IsControllerTypeKeyBoard_ReturnValue; // 0x0D9A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_7;                    // 0x0D9B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_8;                    // 0x0D9C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsBotControlled_ReturnValue_3;            // 0x0D9D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_9;                    // 0x0D9E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D9F[0x1];                                      // 0x0D9F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class URuntimeSaveSubsystem*                  CallFunc_GetLocalPlayerSubsystem_ReturnValue_2;    // 0x0DA0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EAbilityExecOrigin                            Temp_byte_Variable_2;                              // 0x0DA8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_10;                   // 0x0DA9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DAA[0x2];                                      // 0x0DAA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_BPF_GetGameOptionSavedValue_ReturnValue;  // 0x0DAC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_wildcard_Variable_3;                          // 0x0DB0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DB1[0x7];                                      // 0x0DB1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_SelectFloat_ReturnValue;                  // 0x0DB8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAbilityExecOrigin                            CallFunc_BPF_SetNamedBoolTargetData__eOut;         // 0x0DC0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BPF_SetNamedBoolTargetData_ReturnValue;   // 0x0DC1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DC2[0x2];                                      // 0x0DC2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_FTrunc_ReturnValue;                       // 0x0DC4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0DC8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAbilityExecOrigin                            CallFunc_BPF_SetNamedIntegerTargetData__eOut;      // 0x0DC9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DCA[0x2];                                      // 0x0DCA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_BPF_SetNamedIntegerTargetData_ReturnValue; // 0x0DCC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0DD0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess_1;                    // 0x0DD1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DD2[0x6];                                      // 0x0DD2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayEventData                     K2Node_Event_EventData;                            // 0x0DD8(0x00B0)(ConstParm)
	class ARuntimeCharacter*                      CallFunc_BPF_GetRuntimeCharacter_ReturnValue_6;    // 0x0E88(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTargetingContext                      CallFunc_BPF_SaveActorState__targetingContext;     // 0x0E90(0x00E0)()
	struct FGameplayAbilityTargetDataHandle       Temp_struct_Variable_2;                            // 0x0F70(0x0028)(ConstParm)
	bool                                          CallFunc_K2_CommitAbility_ReturnValue;             // 0x0F98(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F99[0x7];                                      // 0x0F99(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayAbilityTargetDataHandle       CallFunc_MakeTargetDataHandle__outHandle_3;        // 0x0FA0(0x0028)()
	struct FActiveGameplayEffectHandle            CallFunc_BP_ApplyGameplayEffectToOwner_ReturnValue_2; // 0x0FC8(0x0008)(NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_29;           // 0x0FD0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTagContainer                  CallFunc_MakeGameplayTagContainerFromTag_ReturnValue; // 0x0FE0(0x0020)()
	class UAbilityTask_HandleLooseGameplayTags*   CallFunc_BPF_HandleLooseGameplayTags_ReturnValue;  // 0x1000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAbilityTask_HandleLooseGameplayTags*   CallFunc_BPF_HandleLooseGameplayTags_ReturnValue_1; // 0x1008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_11;                   // 0x1010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_12;                   // 0x1011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1012[0x6];                                     // 0x1012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayAbilityTargetDataHandle       CallFunc_MakeTargetDataHandle__outHandle_4;        // 0x1018(0x0028)()
	struct FGameplayAbilityTargetDataHandle       CallFunc_BPF_CombineTargetDataCommutative_ReturnValue; // 0x1040(0x0028)()
	struct FGameplayAbilityTargetDataHandle       CallFunc_MakeTargetDataHandle__outHandle_5;        // 0x1068(0x0028)()
	struct FInputGameplayAbilityTargetData        CallFunc_BPF_FindCurrentInputTargetData__outData;  // 0x1090(0x0058)()
	bool                                          CallFunc_BPF_FindCurrentInputTargetData_ReturnValue; // 0x10E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_10E9[0x7];                                     // 0x10E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRTNetworkSyncShootTimeArg             K2Node_MakeStruct_RTNetworkSyncShootTimeArg;       // 0x10F0(0x0028)()
	struct FShootPrepTargetData                   CallFunc_MakeShootPrep_ReturnValue;                // 0x1118(0x00E0)(ContainsInstancedReference)
	struct FRTInputActionsForNetworkSyncShoot     K2Node_MakeStruct_RTInputActionsForNetworkSyncShoot; // 0x11F8(0x0018)(NoDestructor)
	struct FGameplayAbilityTargetDataHandle       CallFunc_MakeShootDirectionTargetData_Result;      // 0x1210(0x0028)()
	class UAbilityTask_HandleLooseGameplayTags*   CallFunc_BPF_HandleLooseGameplayTag_ReturnValue;   // 0x1238(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayAbilityTargetDataHandle       CallFunc_MakeTargetDataHandle__outHandle_6;        // 0x1240(0x0028)()
	ETargetValidationResult                       CallFunc_BPF_ValidateTargetBranch__outResult;      // 0x1268(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_13;                   // 0x1269(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess_2;                    // 0x126A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_126B[0x5];                                     // 0x126B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayAbilityTargetDataHandle       CallFunc_GetProvidedTargetData__outData_3;         // 0x1270(0x0028)()
	struct FGameplayAbilityTargetDataHandle       CallFunc_MakeTargetDataHandle__outHandle_7;        // 0x1298(0x0028)()
	struct FBallInterceptionPointTargetData       CallFunc_GetTargetDataPure__outData_4;             // 0x12C0(0x0120)()
	bool                                          CallFunc_GetTargetDataPure_ReturnValue_4;          // 0x13E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETargetValidationResult                       CallFunc_BPF_ValidateTargetBranch__outResult_1;    // 0x13E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess_3;                    // 0x13E2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_13E3[0x5];                                     // 0x13E3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UAbilityTask_BallInteractionRequest*    CallFunc_BPF_BallInteractionRequest_ReturnValue;   // 0x13E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayAbilityTargetDataHandle       CallFunc_GetProvidedTargetData__outData_4;         // 0x13F0(0x0028)()
	uint8                                         Pad_1418[0x8];                                     // 0x1418(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimSequencePlayInfos                 CallFunc_GetTargetDataPure__outData_5;             // 0x1420(0x0130)()
	bool                                          CallFunc_GetTargetDataPure_ReturnValue_5;          // 0x1550(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_14;                   // 0x1551(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1552[0x6];                                     // 0x1552(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayAbilityTargetDataHandle       CallFunc_GetProvidedTargetData__outData_5;         // 0x1558(0x0028)()
	struct FGameplayAbilityTargetDataHandle       CallFunc_BPF_CombineTargetDataCommutative_ReturnValue_1; // 0x1580(0x0028)()
	class ABall*                                  CallFunc_BPF_GetBall_ReturnValue;                  // 0x15A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FGameplayAbilityTargetDataHandle       CallFunc_BPF_CombineTargetDataCommutative_ReturnValue_2; // 0x15B0(0x0028)()
	class UAbilityTask_ApplyVolleyShoot*          CallFunc_BPF_ApplyVolleyShootTask_ReturnValue;     // 0x15D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FSCConditionsToSyncEarly               Temp_struct_Variable_3;                            // 0x15E0(0x0018)(ConstParm, NoDestructor, ContainsInstancedReference)
	class UAbilityTask_NetworkSyncShootData*      CallFunc_BPF_NetworkSyncShootDataWithInputs_ReturnValue; // 0x15F8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_15;                   // 0x1600(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_16;                   // 0x1601(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1602[0x6];                                     // 0x1602(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  CallFunc_MakeGameplayTagContainerFromTag_ReturnValue_1; // 0x1608(0x0020)()
	class UAbilityTask_HandleLooseGameplayTags*   CallFunc_BPF_HandleLooseGameplayTags_ReturnValue_2; // 0x1628(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_17;                   // 0x1630(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_18;                   // 0x1631(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bWasCancelled;                        // 0x1632(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1633[0x5];                                     // 0x1633(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class ARuntimeCharacter*                      CallFunc_BPF_GetRuntimeCharacter_ReturnValue_7;    // 0x1638(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	EAbilityExecOrigin                            Temp_byte_Variable_3;                              // 0x1640(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAbilityExecOutputWithValidation              CallFunc_BPF_PickAndPlayMontage__eOut;             // 0x1641(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1642[0x6];                                     // 0x1642(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UAbilityTask_SCPlayMontageAndWait*      CallFunc_BPF_PickAndPlayMontage_ReturnValue;       // 0x1648(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_19;                   // 0x1650(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess_4;                    // 0x1651(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1652[0x2];                                     // 0x1652(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_30;           // 0x1654(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1664[0x4];                                     // 0x1664(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwningActorFromActorInfo_ReturnValue_5; // 0x1668(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ARuntimeCharacter*                      K2Node_DynamicCast_AsRuntime_Character_3;          // 0x1670(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_6;                     // 0x1678(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1679[0x7];                                     // 0x1679(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABall*                                  CallFunc_BPF_GetBall_ReturnValue_1;                // 0x1680(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue_1;               // 0x1688(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue_2;                // 0x1689(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BPF_HasBall_ReturnValue_1;                // 0x168A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_168B[0x1];                                     // 0x168B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_31;           // 0x168C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanOR_ReturnValue_1;                  // 0x169C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_169D[0x3];                                     // 0x169D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class ABall*                                  CallFunc_BPF_GetBall_ReturnValue_2;                // 0x16A0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABall*                                  CallFunc_BPF_GetBall_ReturnValue_3;                // 0x16A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_20;                   // 0x16B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_16B1[0x7];                                     // 0x16B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FShootParams                           CallFunc_BPF_GetShootParams__outShootParams;       // 0x16B8(0x0108)()
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_32;           // 0x17C0(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAnimSequenceBase*                      Temp_wildcard_Variable_4;                          // 0x17D0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABall*                                  CallFunc_BPF_GetBall_ReturnValue_4;                // 0x17D8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_21;                   // 0x17E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_22;                   // 0x17E1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_17E2[0x6];                                     // 0x17E2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNotifyEvent                       CallFunc_FindNotifyStateByClass__outFoundNotify_1; // 0x17E8(0x00B8)(ContainsInstancedReference)
	bool                                          CallFunc_FindNotifyStateByClass__bOutFound_1;      // 0x18A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_18A1[0x7];                                     // 0x18A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAbilityTask_HandleGameplayCue*         CallFunc_BPF_HandleGameplayCue_ReturnValue_1;      // 0x18A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_23;                   // 0x18B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_DoubleDouble_ReturnValue;    // 0x18B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAbilityExecOrigin                            CallFunc_BPF_SetNamedBoolTargetData__eOut_1;       // 0x18B2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BPF_SetNamedBoolTargetData_ReturnValue_1; // 0x18B3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_18B4[0x4];                                     // 0x18B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayAbilityTargetDataHandle       CallFunc_MakeTargetDataHandle__outHandle_8;        // 0x18B8(0x0028)()
	bool                                          K2Node_SwitchEnum_CmpSuccess_5;                    // 0x18E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_18E1[0x7];                                     // 0x18E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  CallFunc_BPF_GetAbilityTags_ReturnValue_1;         // 0x18E8(0x0020)()
	EAbilityExecOrigin                            Temp_byte_Variable_4;                              // 0x1908(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1909[0x7];                                     // 0x1909(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayEffectContextHandle           CallFunc_BPF_MakeRuntimeGameplayEffectContextHandle__outHandle_1; // 0x1910(0x0018)()
	struct FGameplayEffectSpecHandle              CallFunc_BPF_MakeGameplaySpecWithContext__outResult; // 0x1928(0x0010)()
	struct FActiveGameplayEffectHandle            CallFunc_K2_ApplyGameplayEffectSpecToOwner_ReturnValue; // 0x1938(0x0008)(NoDestructor, HasGetValueTypeHash)
	EAbilityExecOutputWithValidation              CallFunc_BPF_PickAndPlayMontage__eOut_1;           // 0x1940(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1941[0x7];                                     // 0x1941(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAbilityTask_SCPlayMontageAndWait*      CallFunc_BPF_PickAndPlayMontage_ReturnValue_1;     // 0x1948(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UAbilityTask_HandleLooseGameplayTags*   CallFunc_BPF_HandleLooseGameplayTags_ReturnValue_3; // 0x1950(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_24;                   // 0x1958(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_25;                   // 0x1959(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess_6;                    // 0x195A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_195B[0x5];                                     // 0x195B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimSequenceSnapPrediction            CallFunc_BPF_GetSnapPredictionFromAnimSequencePlayInfos__outSnapPrediction; // 0x1960(0x0020)(NoDestructor)
	bool                                          CallFunc_BPF_GetSnapPredictionFromAnimSequencePlayInfos_ReturnValue; // 0x1980(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1981[0x7];                                     // 0x1981(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAbilityTask_MoveToSnapLocation*        CallFunc_BPF_MoveToSnapLocation_ReturnValue;       // 0x1988(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsGameplayTagValid_ReturnValue;           // 0x1990(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1991[0x7];                                     // 0x1991(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  CallFunc_MakeGameplayTagContainerFromTag_ReturnValue_2; // 0x1998(0x0020)()
	class UAbilityTask_HandleLooseGameplayTags*   CallFunc_BPF_HandleLooseGameplayTags_ReturnValue_4; // 0x19B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_26;                   // 0x19C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_27;                   // 0x19C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19C2[0x2];                                     // 0x19C2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_33;           // 0x19C4(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19D4[0x4];                                     // 0x19D4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_SelectFloat_A_ImplicitCast;               // 0x19D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GA_VolleyTap_C_ExecuteUbergraph_GA_VolleyTap;

// Function GA_VolleyTap.GA_VolleyTap_C.K2_ActivateAbilityFromEvent
// 0x00B0 (0x00B0 - 0x0000)
struct GA_VolleyTap_C_K2_ActivateAbilityFromEvent final
{
public:
	struct FGameplayEventData                     EventData;                                         // 0x0000(0x00B0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_GA_VolleyTap_C_K2_ActivateAbilityFromEvent;

// Function GA_VolleyTap.GA_VolleyTap_C.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct GA_VolleyTap_C_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_GA_VolleyTap_C_K2_OnEndAbility;

// Function GA_VolleyTap.GA_VolleyTap_C.m_BuildClientPayload_E7841AA048F400D304E4C2A9785D632C
// 0x0028 (0x0028 - 0x0000)
struct GA_VolleyTap_C_m_BuildClientPayload_E7841AA048F400D304E4C2A9785D632C final
{
public:
	struct FGameplayAbilityTargetDataHandle       Data;                                              // 0x0000(0x0028)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_GA_VolleyTap_C_m_BuildClientPayload_E7841AA048F400D304E4C2A9785D632C;

// Function GA_VolleyTap.GA_VolleyTap_C.OnCancel_E7841AA048F400D304E4C2A9785D632C
// 0x0028 (0x0028 - 0x0000)
struct GA_VolleyTap_C_OnCancel_E7841AA048F400D304E4C2A9785D632C final
{
public:
	struct FGameplayAbilityTargetDataHandle       Data;                                              // 0x0000(0x0028)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_GA_VolleyTap_C_OnCancel_E7841AA048F400D304E4C2A9785D632C;

// Function GA_VolleyTap.GA_VolleyTap_C.OnSync_E7841AA048F400D304E4C2A9785D632C
// 0x0028 (0x0028 - 0x0000)
struct GA_VolleyTap_C_OnSync_E7841AA048F400D304E4C2A9785D632C final
{
public:
	struct FGameplayAbilityTargetDataHandle       Data;                                              // 0x0000(0x0028)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_GA_VolleyTap_C_OnSync_E7841AA048F400D304E4C2A9785D632C;

// Function GA_VolleyTap.GA_VolleyTap_C.OnTimeOut_E7841AA048F400D304E4C2A9785D632C
// 0x0028 (0x0028 - 0x0000)
struct GA_VolleyTap_C_OnTimeOut_E7841AA048F400D304E4C2A9785D632C final
{
public:
	struct FGameplayAbilityTargetDataHandle       Data;                                              // 0x0000(0x0028)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_GA_VolleyTap_C_OnTimeOut_E7841AA048F400D304E4C2A9785D632C;

// Function GA_VolleyTap.GA_VolleyTap_C.OverrideAimingComputationForKeyBoard
// 0x00C8 (0x00C8 - 0x0000)
struct GA_VolleyTap_C_OverrideAimingComputationForKeyBoard final
{
public:
	int32                                         GameOption;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOverrideDirectionComputationTargetData K2Node_MakeStruct_OverrideDirectionComputationTargetData; // 0x0008(0x0018)()
	struct FOverrideDirectionComputationTargetData K2Node_MakeStruct_OverrideDirectionComputationTargetData_1; // 0x0020(0x0018)()
	struct FGameplayAbilityTargetDataHandle       CallFunc_MakeTargetDataHandle__outHandle;          // 0x0038(0x0028)()
	struct FGameplayAbilityTargetDataHandle       CallFunc_MakeTargetDataHandle__outHandle_1;        // 0x0060(0x0028)()
	struct FOverrideDirectionComputationTargetData K2Node_MakeStruct_OverrideDirectionComputationTargetData_2; // 0x0088(0x0018)()
	struct FGameplayAbilityTargetDataHandle       CallFunc_MakeTargetDataHandle__outHandle_2;        // 0x00A0(0x0028)()
};
DUMPER7_ASSERTS_GA_VolleyTap_C_OverrideAimingComputationForKeyBoard;

// Function GA_VolleyTap.GA_VolleyTap_C.GetPlayerContext
// 0x0320 (0x0320 - 0x0000)
struct GA_VolleyTap_C_GetPlayerContext final
{
public:
	struct FGameplayAbilityTargetDataHandle       Data;                                              // 0x0000(0x0028)(BlueprintVisible, BlueprintReadOnly, Parm)
	struct FGameplayAbilityTargetDataHandle       PlayerContext;                                     // 0x0028(0x0028)(Parm, OutParm)
	struct FAnimSequencePlayInfos                 CallFunc_GetTargetData__outData;                   // 0x0050(0x0130)()
	bool                                          CallFunc_GetTargetData_ReturnValue;                // 0x0180(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_181[0x7];                                      // 0x0181(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayAbilityTargetDataHandle       CallFunc_MakeTargetDataHandle__outHandle;          // 0x0188(0x0028)()
	struct FGameplayAbilityTargetDataHandle       CallFunc_MakeTargetDataHandle__outHandle_1;        // 0x01B0(0x0028)()
	struct FGameplayAbilityTargetDataHandle       CallFunc_MakeTargetDataHandle__outHandle_2;        // 0x01D8(0x0028)()
	struct FGameplayAbilityTargetDataHandle       CallFunc_MakeTargetDataHandle__outHandle_3;        // 0x0200(0x0028)()
	struct FGameplayAbilityTargetDataHandle       CallFunc_BPF_CombineTargetDataCommutative_ReturnValue; // 0x0228(0x0028)()
	struct FGameplayAbilityTargetDataHandle       CallFunc_MakeTargetDataHandle__outHandle_4;        // 0x0250(0x0028)()
	struct FGameplayAbilityTargetDataHandle       CallFunc_BPF_CombineTargetDataCommutative_ReturnValue_1; // 0x0278(0x0028)()
	struct FGameplayAbilityTargetDataHandle       CallFunc_BPF_CombineTargetDataCommutative_ReturnValue_2; // 0x02A0(0x0028)()
	struct FGameplayAbilityTargetDataHandle       CallFunc_BPF_CombineTargetDataCommutative_ReturnValue_3; // 0x02C8(0x0028)()
	struct FGameplayAbilityTargetDataHandle       CallFunc_BPF_CombineTargetDataCommutative_ReturnValue_4; // 0x02F0(0x0028)()
};
DUMPER7_ASSERTS_GA_VolleyTap_C_GetPlayerContext;

// Function GA_VolleyTap.GA_VolleyTap_C.MakeShootPrep
// 0x0370 (0x0370 - 0x0000)
struct GA_VolleyTap_C_MakeShootPrep final
{
public:
	struct FShootPrepTargetData                   ReturnValue;                                       // 0x0000(0x00E0)(Parm, OutParm, ReturnParm, ContainsInstancedReference)
	struct FGameplayAbilityTargetDataHandle       CallFunc_GetProvidedTargetData__outData;           // 0x00E0(0x0028)()
	struct FGameplayAbilityTargetDataHandle       CallFunc_GetProvidedTargetData__outData_1;         // 0x0108(0x0028)()
	struct FBallInterceptionPointTargetData       CallFunc_GetTargetDataPure__outData;               // 0x0130(0x0120)()
	bool                                          CallFunc_GetTargetDataPure_ReturnValue;            // 0x0250(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_251[0x7];                                      // 0x0251(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayAbilityTargetDataHandle       CallFunc_BPF_CombineTargetDataCommutative_ReturnValue; // 0x0258(0x0028)()
	class ABall*                                  CallFunc_BPF_GetBall_ReturnValue;                  // 0x0280(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FShootPrepTargetData                   CallFunc_BPF_MakePrepTargetDataFromClass_ReturnValue; // 0x0288(0x00E0)(ContainsInstancedReference)
};
DUMPER7_ASSERTS_GA_VolleyTap_C_MakeShootPrep;

}

