#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_Fidget

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GC_Fidget.GC_Fidget_C
// 0x0000 (0x0040 - 0x0040)
class UGC_Fidget_C final : public UGameplayCueNotify_Static
{
public:
	bool OnActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters) const;
	bool OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GC_Fidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GC_Fidget_C")
	}
	static class UGC_Fidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGC_Fidget_C>();
	}
};
DUMPER7_ASSERTS_UGC_Fidget_C;

}

