#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_CharacterDefaultAbilities

#include "Basic.hpp"

#include "Runtime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_CharacterDefaultAbilities.GE_CharacterDefaultAbilities_C
// 0x0000 (0x0B00 - 0x0B00)
class UGE_CharacterDefaultAbilities_C final : public URuntimeGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_CharacterDefaultAbilities_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_CharacterDefaultAbilities_C")
	}
	static class UGE_CharacterDefaultAbilities_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_CharacterDefaultAbilities_C>();
	}
};
DUMPER7_ASSERTS_UGE_CharacterDefaultAbilities_C;

}

