#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_Cooldown_Regen

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Cooldown_Regen.GE_Cooldown_Regen_C
// 0x0000 (0x0B00 - 0x0B00)
class UGE_Cooldown_Regen_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_Cooldown_Regen_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_Cooldown_Regen_C")
	}
	static class UGE_Cooldown_Regen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Cooldown_Regen_C>();
	}
};
DUMPER7_ASSERTS_UGE_Cooldown_Regen_C;

}

