#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GenericAll_ButAnyShootOrControl

#include "Basic.hpp"

#include "SCCore_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GenericAll_ButAnyShootOrControl.GenericAll_ButAnyShootOrControl_C
// 0x0000 (0x00A0 - 0x00A0)
class UGenericAll_ButAnyShootOrControl_C final : public UTagAvailabilityLayerContainer
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GenericAll_ButAnyShootOrControl_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GenericAll_ButAnyShootOrControl_C")
	}
	static class UGenericAll_ButAnyShootOrControl_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGenericAll_ButAnyShootOrControl_C>();
	}
};
DUMPER7_ASSERTS_UGenericAll_ButAnyShootOrControl_C;

}

