#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HighPowerAfterShootScaleSpeedData

#include "Basic.hpp"

#include "SCCore_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HighPowerAfterShootScaleSpeedData.HighPowerAfterShootScaleSpeedData_C
// 0x0000 (0x0170 - 0x0170)
class UHighPowerAfterShootScaleSpeedData_C final : public UScaleSpeedRootMotionModifierData
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HighPowerAfterShootScaleSpeedData_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HighPowerAfterShootScaleSpeedData_C")
	}
	static class UHighPowerAfterShootScaleSpeedData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHighPowerAfterShootScaleSpeedData_C>();
	}
};
DUMPER7_ASSERTS_UHighPowerAfterShootScaleSpeedData_C;

}

