#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InDiveOutfield_CameraTransition

#include "Basic.hpp"

#include "TemplateDefault_CameraTransition_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass InDiveOutfield_CameraTransition.InDiveOutfield_CameraTransition_C
// 0x0000 (0x0058 - 0x0058)
class UInDiveOutfield_CameraTransition_C final : public UTemplateDefault_CameraTransition_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("InDiveOutfield_CameraTransition_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"InDiveOutfield_CameraTransition_C")
	}
	static class UInDiveOutfield_CameraTransition_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInDiveOutfield_CameraTransition_C>();
	}
};
DUMPER7_ASSERTS_UInDiveOutfield_CameraTransition_C;

}

