#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LobbedPushBallBuildUpData

#include "Basic.hpp"

#include "SCCore_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LobbedPushBallBuildUpData.LobbedPushBallBuildUpData_C
// 0x0000 (0x0170 - 0x0170)
class ULobbedPushBallBuildUpData_C final : public UScaleSpeedRootMotionModifierData
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LobbedPushBallBuildUpData_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LobbedPushBallBuildUpData_C")
	}
	static class ULobbedPushBallBuildUpData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULobbedPushBallBuildUpData_C>();
	}
};
DUMPER7_ASSERTS_ULobbedPushBallBuildUpData_C;

}

