#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LobbedPushBallDashData

#include "Basic.hpp"

#include "SCCore_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LobbedPushBallDashData.LobbedPushBallDashData_C
// 0x0000 (0x0170 - 0x0170)
class ULobbedPushBallDashData_C final : public UScaleSpeedRootMotionModifierData
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LobbedPushBallDashData_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LobbedPushBallDashData_C")
	}
	static class ULobbedPushBallDashData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULobbedPushBallDashData_C>();
	}
};
DUMPER7_ASSERTS_ULobbedPushBallDashData_C;

}

