#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MenuFlow_HomeTransition_Lighting

#include "Basic.hpp"

#include "MenuFlow_HomeTransition_Lighting_classes.hpp"
#include "MenuFlow_HomeTransition_Lighting_parameters.hpp"


namespace SDK
{

// Function MenuFlow_HomeTransition_Lighting.MenuFlow_HomeTransition_Lighting_DirectorBP_C.ChangingRoom_MultiFog_OFF
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AMultiFog*                        ChangingRoom_MultiFog                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UMenuFlow_HomeTransition_Lighting_DirectorBP_C::ChangingRoom_MultiFog_OFF(class AMultiFog* ChangingRoom_MultiFog)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MenuFlow_HomeTransition_Lighting_DirectorBP_C", "ChangingRoom_MultiFog_OFF");

	Params::MenuFlow_HomeTransition_Lighting_DirectorBP_C_ChangingRoom_MultiFog_OFF Parms{};

	Parms.ChangingRoom_MultiFog = ChangingRoom_MultiFog;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MenuFlow_HomeTransition_Lighting.MenuFlow_HomeTransition_Lighting_DirectorBP_C.ColiseumMultiFog_ON
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AMultiFog*                        MultiFog                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UMenuFlow_HomeTransition_Lighting_DirectorBP_C::ColiseumMultiFog_ON(class AMultiFog* MultiFog)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MenuFlow_HomeTransition_Lighting_DirectorBP_C", "ColiseumMultiFog_ON");

	Params::MenuFlow_HomeTransition_Lighting_DirectorBP_C_ColiseumMultiFog_ON Parms{};

	Parms.MultiFog = MultiFog;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MenuFlow_HomeTransition_Lighting.MenuFlow_HomeTransition_Lighting_DirectorBP_C.ExecuteUbergraph_MenuFlow_HomeTransition_Lighting_DirectorBP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMenuFlow_HomeTransition_Lighting_DirectorBP_C::ExecuteUbergraph_MenuFlow_HomeTransition_Lighting_DirectorBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MenuFlow_HomeTransition_Lighting_DirectorBP_C", "ExecuteUbergraph_MenuFlow_HomeTransition_Lighting_DirectorBP");

	Params::MenuFlow_HomeTransition_Lighting_DirectorBP_C_ExecuteUbergraph_MenuFlow_HomeTransition_Lighting_DirectorBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MenuFlow_HomeTransition_Lighting.MenuFlow_HomeTransition_Lighting_DirectorBP_C.LGT_Field_Sun_01_ON
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ADirectionalLight*                LGT_Field_Sun_01                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UMenuFlow_HomeTransition_Lighting_DirectorBP_C::LGT_Field_Sun_01_ON(class ADirectionalLight* LGT_Field_Sun_01)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MenuFlow_HomeTransition_Lighting_DirectorBP_C", "LGT_Field_Sun_01_ON");

	Params::MenuFlow_HomeTransition_Lighting_DirectorBP_C_LGT_Field_Sun_01_ON Parms{};

	Parms.LGT_Field_Sun_01 = LGT_Field_Sun_01;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MenuFlow_HomeTransition_Lighting.MenuFlow_HomeTransition_Lighting_DirectorBP_C.LGT_Sky_01_ON
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASkyLight*                        LGT_Sky_01                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UMenuFlow_HomeTransition_Lighting_DirectorBP_C::LGT_Sky_01_ON(class ASkyLight* LGT_Sky_01)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MenuFlow_HomeTransition_Lighting_DirectorBP_C", "LGT_Sky_01_ON");

	Params::MenuFlow_HomeTransition_Lighting_DirectorBP_C_LGT_Sky_01_ON Parms{};

	Parms.LGT_Sky_01 = LGT_Sky_01;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MenuFlow_HomeTransition_Lighting.MenuFlow_HomeTransition_Lighting_DirectorBP_C.LGT_Sky_ChangingRoom_01_OFF
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASkyLight*                        LGT_Sky_ChangingRoom_01                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UMenuFlow_HomeTransition_Lighting_DirectorBP_C::LGT_Sky_ChangingRoom_01_OFF(class ASkyLight* LGT_Sky_ChangingRoom_01)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MenuFlow_HomeTransition_Lighting_DirectorBP_C", "LGT_Sky_ChangingRoom_01_OFF");

	Params::MenuFlow_HomeTransition_Lighting_DirectorBP_C_LGT_Sky_ChangingRoom_01_OFF Parms{};

	Parms.LGT_Sky_ChangingRoom_01 = LGT_Sky_ChangingRoom_01;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MenuFlow_HomeTransition_Lighting.MenuFlow_HomeTransition_Lighting_DirectorBP_C.LGT_TrainingCenter_Sun_01_ON
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ADirectionalLight*                LGT_TrainingCenter_Sun_01                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UMenuFlow_HomeTransition_Lighting_DirectorBP_C::LGT_TrainingCenter_Sun_01_ON(class ADirectionalLight* LGT_TrainingCenter_Sun_01)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MenuFlow_HomeTransition_Lighting_DirectorBP_C", "LGT_TrainingCenter_Sun_01_ON");

	Params::MenuFlow_HomeTransition_Lighting_DirectorBP_C_LGT_TrainingCenter_Sun_01_ON Parms{};

	Parms.LGT_TrainingCenter_Sun_01 = LGT_TrainingCenter_Sun_01;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MenuFlow_HomeTransition_Lighting.MenuFlow_HomeTransition_Lighting_DirectorBP_C.SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASkyLight*                        LGT_Sky_01                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UMenuFlow_HomeTransition_Lighting_DirectorBP_C::SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP(class ASkyLight* LGT_Sky_01)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MenuFlow_HomeTransition_Lighting_DirectorBP_C", "SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP");

	Params::MenuFlow_HomeTransition_Lighting_DirectorBP_C_SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP Parms{};

	Parms.LGT_Sky_01 = LGT_Sky_01;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MenuFlow_HomeTransition_Lighting.MenuFlow_HomeTransition_Lighting_DirectorBP_C.SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_0
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ASkyLight*                        LGT_Sky_ChangingRoom_01                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UMenuFlow_HomeTransition_Lighting_DirectorBP_C::SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_0(class ASkyLight* LGT_Sky_ChangingRoom_01)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MenuFlow_HomeTransition_Lighting_DirectorBP_C", "SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_0");

	Params::MenuFlow_HomeTransition_Lighting_DirectorBP_C_SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_0 Parms{};

	Parms.LGT_Sky_ChangingRoom_01 = LGT_Sky_ChangingRoom_01;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MenuFlow_HomeTransition_Lighting.MenuFlow_HomeTransition_Lighting_DirectorBP_C.SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_1
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ADirectionalLight*                LGT_Field_Sun_01                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UMenuFlow_HomeTransition_Lighting_DirectorBP_C::SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_1(class ADirectionalLight* LGT_Field_Sun_01)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MenuFlow_HomeTransition_Lighting_DirectorBP_C", "SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_1");

	Params::MenuFlow_HomeTransition_Lighting_DirectorBP_C_SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_1 Parms{};

	Parms.LGT_Field_Sun_01 = LGT_Field_Sun_01;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MenuFlow_HomeTransition_Lighting.MenuFlow_HomeTransition_Lighting_DirectorBP_C.SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_2
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AMultiFog*                        MultiFog                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UMenuFlow_HomeTransition_Lighting_DirectorBP_C::SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_2(class AMultiFog* MultiFog)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MenuFlow_HomeTransition_Lighting_DirectorBP_C", "SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_2");

	Params::MenuFlow_HomeTransition_Lighting_DirectorBP_C_SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_2 Parms{};

	Parms.MultiFog = MultiFog;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MenuFlow_HomeTransition_Lighting.MenuFlow_HomeTransition_Lighting_DirectorBP_C.SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_3
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AMultiFog*                        ChangingRoom_MultiFog                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UMenuFlow_HomeTransition_Lighting_DirectorBP_C::SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_3(class AMultiFog* ChangingRoom_MultiFog)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MenuFlow_HomeTransition_Lighting_DirectorBP_C", "SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_3");

	Params::MenuFlow_HomeTransition_Lighting_DirectorBP_C_SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_3 Parms{};

	Parms.ChangingRoom_MultiFog = ChangingRoom_MultiFog;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MenuFlow_HomeTransition_Lighting.MenuFlow_HomeTransition_Lighting_DirectorBP_C.SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_4
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ADirectionalLight*                LGT_TrainingCenter_Sun_01                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UMenuFlow_HomeTransition_Lighting_DirectorBP_C::SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_4(class ADirectionalLight* LGT_TrainingCenter_Sun_01)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MenuFlow_HomeTransition_Lighting_DirectorBP_C", "SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_4");

	Params::MenuFlow_HomeTransition_Lighting_DirectorBP_C_SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_Lighting_DirectorBP_4 Parms{};

	Parms.LGT_TrainingCenter_Sun_01 = LGT_TrainingCenter_Sun_01;

	UObject::ProcessEvent(Func, &Parms);
}

}

