#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MenuFlow_BattlePass_To_Body

#include "Basic.hpp"

#include "LevelSequence_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MenuFlow_BattlePass_To_Body.MenuFlow_BattlePass_To_Body_DirectorBP_C
// 0x0000 (0x0050 - 0x0050)
class UMenuFlow_BattlePass_To_Body_DirectorBP_C final : public ULevelSequenceDirector
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MenuFlow_BattlePass_To_Body_DirectorBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MenuFlow_BattlePass_To_Body_DirectorBP_C")
	}
	static class UMenuFlow_BattlePass_To_Body_DirectorBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMenuFlow_BattlePass_To_Body_DirectorBP_C>();
	}
};
DUMPER7_ASSERTS_UMenuFlow_BattlePass_To_Body_DirectorBP_C;

}

