#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MenuFlow_HomeTransition

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "LevelSequence_classes.hpp"
#include "AkAudio_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass MenuFlow_HomeTransition.MenuFlow_HomeTransition_DirectorBP_C
// 0x0008 (0x0058 - 0x0050)
class UMenuFlow_HomeTransition_DirectorBP_C final : public ULevelSequenceDirector
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0050(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void AudioTransitionIn_Home();
	void ExecuteUbergraph_MenuFlow_HomeTransition_DirectorBP(int32 EntryPoint);
	void SequenceEvent__ENTRYPOINTMenuFlow_HomeTransition_DirectorBP();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MenuFlow_HomeTransition_DirectorBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MenuFlow_HomeTransition_DirectorBP_C")
	}
	static class UMenuFlow_HomeTransition_DirectorBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMenuFlow_HomeTransition_DirectorBP_C>();
	}
};
DUMPER7_ASSERTS_UMenuFlow_HomeTransition_DirectorBP_C;

}

