#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NoDeflect_Base_BallStatus

#include "Basic.hpp"

#include "Runtime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NoDeflect_Base_BallStatus.NoDeflect_Base_BallStatus_C
// 0x0000 (0x0050 - 0x0050)
class UNoDeflect_Base_BallStatus_C : public UTrajectoryStatus
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NoDeflect_Base_BallStatus_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NoDeflect_Base_BallStatus_C")
	}
	static class UNoDeflect_Base_BallStatus_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNoDeflect_Base_BallStatus_C>();
	}
};
DUMPER7_ASSERTS_UNoDeflect_Base_BallStatus_C;

}

