#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NoDeflect_Shoot_BallStatus

#include "Basic.hpp"

#include "NoDeflect_Base_BallStatus_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NoDeflect_Shoot_BallStatus.NoDeflect_Shoot_BallStatus_C
// 0x0000 (0x0050 - 0x0050)
class UNoDeflect_Shoot_BallStatus_C final : public UNoDeflect_Base_BallStatus_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("NoDeflect_Shoot_BallStatus_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"NoDeflect_Shoot_BallStatus_C")
	}
	static class UNoDeflect_Shoot_BallStatus_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNoDeflect_Shoot_BallStatus_C>();
	}
};
DUMPER7_ASSERTS_UNoDeflect_Shoot_BallStatus_C;

}

