#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OutShoot_CameraTransition

#include "Basic.hpp"

#include "TemplateDefault_CameraTransition_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass OutShoot_CameraTransition.OutShoot_CameraTransition_C
// 0x0000 (0x0058 - 0x0058)
class UOutShoot_CameraTransition_C final : public UTemplateDefault_CameraTransition_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("OutShoot_CameraTransition_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"OutShoot_CameraTransition_C")
	}
	static class UOutShoot_CameraTransition_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOutShoot_CameraTransition_C>();
	}
};
DUMPER7_ASSERTS_UOutShoot_CameraTransition_C;

}

