#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PostVolley_BallStatus

#include "Basic.hpp"

#include "Runtime_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PostVolley_BallStatus.PostVolley_BallStatus_C
// 0x0000 (0x0050 - 0x0050)
class UPostVolley_BallStatus_C final : public UTrajectoryStatus
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PostVolley_BallStatus_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PostVolley_BallStatus_C")
	}
	static class UPostVolley_BallStatus_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPostVolley_BallStatus_C>();
	}
};
DUMPER7_ASSERTS_UPostVolley_BallStatus_C;

}

