#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SEQ_TransitionSequence_Screen_Masked

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "LevelSequence_classes.hpp"
#include "AkAudio_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass SEQ_TransitionSequence_Screen_Masked.SEQ_TransitionSequence_Screen_Masked_DirectorBP_C
// 0x0008 (0x0058 - 0x0050)
class USEQ_TransitionSequence_Screen_Masked_DirectorBP_C final : public ULevelSequenceDirector
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0050(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_SEQ_TransitionSequence_Screen_Masked_DirectorBP(int32 EntryPoint);
	struct FMovieSceneDynamicBindingResolveResult Get_Scene_Portal_Binding();
	struct FMovieSceneDynamicBindingResolveResult Get_Stadium_AR_Binding();
	void Get_Stadium_AR_Subsystem(class URuntimeStadiumAR** Subsystem);
	void SequenceEvent(class UAkAudioEvent* AkEvent);
	struct FMovieSceneDynamicBindingResolveResult SequenceEvent__ENTRYPOINTSEQ_TransitionSequence_Screen_Masked_DirectorBP();
	struct FMovieSceneDynamicBindingResolveResult SequenceEvent__ENTRYPOINTSEQ_TransitionSequence_Screen_Masked_DirectorBP_0();
	struct FMovieSceneDynamicBindingResolveResult SequenceEvent__ENTRYPOINTSEQ_TransitionSequence_Screen_Masked_DirectorBP_1();
	struct FMovieSceneDynamicBindingResolveResult Spawn_NS_in_World_AR_Dynamic_Binding();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SEQ_TransitionSequence_Screen_Masked_DirectorBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SEQ_TransitionSequence_Screen_Masked_DirectorBP_C")
	}
	static class USEQ_TransitionSequence_Screen_Masked_DirectorBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USEQ_TransitionSequence_Screen_Masked_DirectorBP_C>();
	}
};
DUMPER7_ASSERTS_USEQ_TransitionSequence_Screen_Masked_DirectorBP_C;

}

