#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Shoot_CameraData_Market

#include "Basic.hpp"

#include "Template_CameraData_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Shoot_CameraData_Market.Shoot_CameraData_Market_C
// 0x0000 (0x02E0 - 0x02E0)
class UShoot_CameraData_Market_C final : public UTemplate_CameraData_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Shoot_CameraData_Market_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Shoot_CameraData_Market_C")
	}
	static class UShoot_CameraData_Market_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UShoot_CameraData_Market_C>();
	}
};
DUMPER7_ASSERTS_UShoot_CameraData_Market_C;

}

