#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TxtStyle_SubHeading_Dark

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TxtStyle_SubHeading_Dark.TxtStyle_SubHeading_Dark_C
// 0x0000 (0x01B0 - 0x01B0)
class UTxtStyle_SubHeading_Dark_C final : public UCommonTextStyle
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TxtStyle_SubHeading_Dark_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TxtStyle_SubHeading_Dark_C")
	}
	static class UTxtStyle_SubHeading_Dark_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTxtStyle_SubHeading_Dark_C>();
	}
};
DUMPER7_ASSERTS_UTxtStyle_SubHeading_Dark_C;

}

