#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_PopupOptionButton_Store

#include "Basic.hpp"

#include "WBP_PopupOptionButton_Store_classes.hpp"
#include "WBP_PopupOptionButton_Store_parameters.hpp"


namespace SDK
{

// Function WBP_PopupOptionButton_Store.WBP_PopupOptionButton_Store_C.FocusButton
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ButtonFocused                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_PopupOptionButton_Store_C::FocusButton(bool ButtonFocused)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PopupOptionButton_Store_C", "FocusButton");

	Params::WBP_PopupOptionButton_Store_C_FocusButton Parms{};

	Parms.ButtonFocused = ButtonFocused;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PopupOptionButton_Store.WBP_PopupOptionButton_Store_C.OnItemViewModelChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USOSBindingsStoreItemViewModel*   viewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_PopupOptionButton_Store_C::OnItemViewModelChanged(class USOSBindingsStoreItemViewModel* viewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PopupOptionButton_Store_C", "OnItemViewModelChanged");

	Params::WBP_PopupOptionButton_Store_C_OnItemViewModelChanged Parms{};

	Parms.viewModel = viewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PopupOptionButton_Store.WBP_PopupOptionButton_Store_C.RefreshButton
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_PopupOptionButton_Store_C::RefreshButton()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PopupOptionButton_Store_C", "RefreshButton");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_PopupOptionButton_Store.WBP_PopupOptionButton_Store_C.SetSCPopupActionViewModel
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USCPopupActionViewModel*          viewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_PopupOptionButton_Store_C::SetSCPopupActionViewModel(class USCPopupActionViewModel* viewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PopupOptionButton_Store_C", "SetSCPopupActionViewModel");

	Params::WBP_PopupOptionButton_Store_C_SetSCPopupActionViewModel Parms{};

	Parms.viewModel = viewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PopupOptionButton_Store.WBP_PopupOptionButton_Store_C.SetSOSBindingsStoreBundleViewModel
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USOSBindingsStoreBundleViewModel* viewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_PopupOptionButton_Store_C::SetSOSBindingsStoreBundleViewModel(class USOSBindingsStoreBundleViewModel* viewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PopupOptionButton_Store_C", "SetSOSBindingsStoreBundleViewModel");

	Params::WBP_PopupOptionButton_Store_C_SetSOSBindingsStoreBundleViewModel Parms{};

	Parms.viewModel = viewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PopupOptionButton_Store.WBP_PopupOptionButton_Store_C.SetSOSBindingsStoreItemViewModel
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USOSBindingsStoreItemViewModel*   viewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_PopupOptionButton_Store_C::SetSOSBindingsStoreItemViewModel(class USOSBindingsStoreItemViewModel* viewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PopupOptionButton_Store_C", "SetSOSBindingsStoreItemViewModel");

	Params::WBP_PopupOptionButton_Store_C_SetSOSBindingsStoreItemViewModel Parms{};

	Parms.viewModel = viewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PopupOptionButton_Store.WBP_PopupOptionButton_Store_C.UpdateOption
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              OptionTag                                              (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UWBP_PopupOptionButton_Store_C::UpdateOption(const struct FGameplayTag& OptionTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PopupOptionButton_Store_C", "UpdateOption");

	Params::WBP_PopupOptionButton_Store_C_UpdateOption Parms{};

	Parms.OptionTag = std::move(OptionTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_PopupOptionButton_Store.WBP_PopupOptionButton_Store_C.GetItemViewModel
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class USOSBindingsStoreItemViewModel**  viewModel                                              (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_PopupOptionButton_Store_C::GetItemViewModel(class USOSBindingsStoreItemViewModel** viewModel) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_PopupOptionButton_Store_C", "GetItemViewModel");

	Params::WBP_PopupOptionButton_Store_C_GetItemViewModel Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (viewModel != nullptr)
		*viewModel = Parms.viewModel;
}

}

