#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_LaunchScreen_Content

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_LaunchScreen_Content.WBP_LaunchScreen_Content_C.ExecuteUbergraph_WBP_LaunchScreen_Content
// 0x0020 (0x0020 - 0x0000)
struct WBP_LaunchScreen_Content_C_ExecuteUbergraph_WBP_LaunchScreen_Content final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetSeasonName_Name;                       // 0x0008(0x0010)()
	class UUMGSequencePlayer*                     CallFunc_PlayAnimationForward_ReturnValue;         // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_LaunchScreen_Content_C_ExecuteUbergraph_WBP_LaunchScreen_Content;

}

