#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Abstract_Common

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "SCCore_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Abstract_Common.WBP_Abstract_Common_C
// 0x0010 (0x0C00 - 0x0BF0)
class UWBP_Abstract_Common_C : public USCUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0BF0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAkStateValue*                          AkState;                                           // 0x0BF8(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

public:
	void BP_OnActivated();
	void ExecuteUbergraph_WBP_Abstract_Common(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_Abstract_Common_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_Abstract_Common_C")
	}
	static class UWBP_Abstract_Common_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Abstract_Common_C>();
	}
};
DUMPER7_ASSERTS_UWBP_Abstract_Common_C;

}

