#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_SeasonEnd_Stats

#include "Basic.hpp"

#include "WBP_SeasonEnd_Stats_classes.hpp"
#include "WBP_SeasonEnd_Stats_parameters.hpp"


namespace SDK
{

// Function WBP_SeasonEnd_Stats.WBP_SeasonEnd_Stats_C.ExecuteUbergraph_WBP_SeasonEnd_Stats
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_SeasonEnd_Stats_C::ExecuteUbergraph_WBP_SeasonEnd_Stats(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEnd_Stats_C", "ExecuteUbergraph_WBP_SeasonEnd_Stats");

	Params::WBP_SeasonEnd_Stats_C_ExecuteUbergraph_WBP_SeasonEnd_Stats Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SeasonEnd_Stats.WBP_SeasonEnd_Stats_C.PlayFadeInAnim
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_SeasonEnd_Stats_C::PlayFadeInAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEnd_Stats_C", "PlayFadeInAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SeasonEnd_Stats.WBP_SeasonEnd_Stats_C.PostEvent
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAkAudioEvent*                    AkEvent                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_SeasonEnd_Stats_C::PostEvent(class UAkAudioEvent* AkEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEnd_Stats_C", "PostEvent");

	Params::WBP_SeasonEnd_Stats_C_PostEvent Parms{};

	Parms.AkEvent = AkEvent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SeasonEnd_Stats.WBP_SeasonEnd_Stats_C.SequenceEvent__ENTRYPOINTWBP_SeasonEnd_Stats
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_SeasonEnd_Stats_C::SequenceEvent__ENTRYPOINTWBP_SeasonEnd_Stats()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEnd_Stats_C", "SequenceEvent__ENTRYPOINTWBP_SeasonEnd_Stats");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_SeasonEnd_Stats.WBP_SeasonEnd_Stats_C.SetSOSPlayerProfileStatisticsViewData
// (Final, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class USOSPlayerProfileStatisticsViewData*viewModel                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_SeasonEnd_Stats_C::SetSOSPlayerProfileStatisticsViewData(class USOSPlayerProfileStatisticsViewData* viewModel)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEnd_Stats_C", "SetSOSPlayerProfileStatisticsViewData");

	Params::WBP_SeasonEnd_Stats_C_SetSOSPlayerProfileStatisticsViewData Parms{};

	Parms.viewModel = viewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_SeasonEnd_Stats.WBP_SeasonEnd_Stats_C.__172fcaa3-416b-466a-7b74-bd9f1acacc47_SourceToDest
// (Final, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText*                            FormattedValue                                         (Parm, OutParm)

void UWBP_SeasonEnd_Stats_C::__172fcaa3_416b_466a_7b74_bd9f1acacc47_SourceToDest(class FText* FormattedValue) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEnd_Stats_C", "__172fcaa3-416b-466a-7b74-bd9f1acacc47_SourceToDest");

	Params::WBP_SeasonEnd_Stats_C___172fcaa3_416b_466a_7b74_bd9f1acacc47_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FormattedValue != nullptr)
		*FormattedValue = std::move(Parms.FormattedValue);
}


// Function WBP_SeasonEnd_Stats.WBP_SeasonEnd_Stats_C.__442a377c-4ba4-201a-bace-dbaf1215de63_SourceToDest
// (Final, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText*                            FormattedValue                                         (Parm, OutParm)

void UWBP_SeasonEnd_Stats_C::__442a377c_4ba4_201a_bace_dbaf1215de63_SourceToDest(class FText* FormattedValue) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEnd_Stats_C", "__442a377c-4ba4-201a-bace-dbaf1215de63_SourceToDest");

	Params::WBP_SeasonEnd_Stats_C___442a377c_4ba4_201a_bace_dbaf1215de63_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FormattedValue != nullptr)
		*FormattedValue = std::move(Parms.FormattedValue);
}


// Function WBP_SeasonEnd_Stats.WBP_SeasonEnd_Stats_C.__4f3089b1-4222-064a-7e06-b490d2cf9568_SourceToDest
// (Final, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText*                            FormattedValue                                         (Parm, OutParm)

void UWBP_SeasonEnd_Stats_C::__4f3089b1_4222_064a_7e06_b490d2cf9568_SourceToDest(class FText* FormattedValue) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEnd_Stats_C", "__4f3089b1-4222-064a-7e06-b490d2cf9568_SourceToDest");

	Params::WBP_SeasonEnd_Stats_C___4f3089b1_4222_064a_7e06_b490d2cf9568_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FormattedValue != nullptr)
		*FormattedValue = std::move(Parms.FormattedValue);
}


// Function WBP_SeasonEnd_Stats.WBP_SeasonEnd_Stats_C.__681cd720-48df-9e1a-e4cc-8f9ab61ee1f0_SourceToDest
// (Final, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText*                            FormattedValue                                         (Parm, OutParm)

void UWBP_SeasonEnd_Stats_C::__681cd720_48df_9e1a_e4cc_8f9ab61ee1f0_SourceToDest(class FText* FormattedValue) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEnd_Stats_C", "__681cd720-48df-9e1a-e4cc-8f9ab61ee1f0_SourceToDest");

	Params::WBP_SeasonEnd_Stats_C___681cd720_48df_9e1a_e4cc_8f9ab61ee1f0_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FormattedValue != nullptr)
		*FormattedValue = std::move(Parms.FormattedValue);
}


// Function WBP_SeasonEnd_Stats.WBP_SeasonEnd_Stats_C.__76667c93-4aa8-569a-3b10-50aa2e6072e9_SourceToDest
// (Final, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText*                            FormattedValue                                         (Parm, OutParm)

void UWBP_SeasonEnd_Stats_C::__76667c93_4aa8_569a_3b10_50aa2e6072e9_SourceToDest(class FText* FormattedValue) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEnd_Stats_C", "__76667c93-4aa8-569a-3b10-50aa2e6072e9_SourceToDest");

	Params::WBP_SeasonEnd_Stats_C___76667c93_4aa8_569a_3b10_50aa2e6072e9_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FormattedValue != nullptr)
		*FormattedValue = std::move(Parms.FormattedValue);
}


// Function WBP_SeasonEnd_Stats.WBP_SeasonEnd_Stats_C.__87281c0a-4c0e-e815-104f-5e9ee6f08e61_SourceToDest
// (Final, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText*                            FormattedValue                                         (Parm, OutParm)

void UWBP_SeasonEnd_Stats_C::__87281c0a_4c0e_e815_104f_5e9ee6f08e61_SourceToDest(class FText* FormattedValue) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEnd_Stats_C", "__87281c0a-4c0e-e815-104f-5e9ee6f08e61_SourceToDest");

	Params::WBP_SeasonEnd_Stats_C___87281c0a_4c0e_e815_104f_5e9ee6f08e61_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FormattedValue != nullptr)
		*FormattedValue = std::move(Parms.FormattedValue);
}


// Function WBP_SeasonEnd_Stats.WBP_SeasonEnd_Stats_C.__8983e45e-4d37-bf2a-22e7-6d8a22c20ca4_SourceToDest
// (Final, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText*                            FormattedValue                                         (Parm, OutParm)

void UWBP_SeasonEnd_Stats_C::__8983e45e_4d37_bf2a_22e7_6d8a22c20ca4_SourceToDest(class FText* FormattedValue) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEnd_Stats_C", "__8983e45e-4d37-bf2a-22e7-6d8a22c20ca4_SourceToDest");

	Params::WBP_SeasonEnd_Stats_C___8983e45e_4d37_bf2a_22e7_6d8a22c20ca4_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FormattedValue != nullptr)
		*FormattedValue = std::move(Parms.FormattedValue);
}


// Function WBP_SeasonEnd_Stats.WBP_SeasonEnd_Stats_C.__e7d7713d-48b8-4f83-5812-c1a89e696a81_SourceToDest
// (Final, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// class FText*                            FormattedValue                                         (Parm, OutParm)

void UWBP_SeasonEnd_Stats_C::__e7d7713d_48b8_4f83_5812_c1a89e696a81_SourceToDest(class FText* FormattedValue) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_SeasonEnd_Stats_C", "__e7d7713d-48b8-4f83-5812-c1a89e696a81_SourceToDest");

	Params::WBP_SeasonEnd_Stats_C___e7d7713d_48b8_4f83_5812_c1a89e696a81_SourceToDest Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (FormattedValue != nullptr)
		*FormattedValue = std::move(Parms.FormattedValue);
}

}

